# Generated by Django 3.2.18 on 2023-07-06 20:28

from django.db import migrations
from slugify import slugify

ELY_PLACE = 'Ely Place'
INFLUENT = 'Influent'


def rename_ely_place(apps, schema_editor):
    Company = apps.get_model('companies', 'Company')
    Card = apps.get_model('cards', 'Workflow')
    try:
        company = Company.objects.filter(name__iexact=ELY_PLACE).first()
        cards = Card.objects.filter(company=company)
        for card in cards:
            if ELY_PLACE in card.name:
                updated_card_name = card.name.replace(ELY_PLACE, INFLUENT)
                card.name = updated_card_name
                card.slug = slugify(updated_card_name)
                card.save()
        company.name = INFLUENT
        company.slug = slugify(INFLUENT)
        company.save()
    except:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0041_auto_20230519_1335'),
    ]

    operations = [
        migrations.RunPython(rename_ely_place)
    ]
