# Generated by Django 3.2.20 on 2023-08-28 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0041_alter_company_logo'),
        ('companies', '0042_auto_20230706_2028'),
    ]

    operations = [
    ]
