# Generated by Django 3.2.16 on 2023-03-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0042_auto_20230706_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='document_system',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Document Push'), (2, 'Sidecar is the documents and records system')], default=1),
        ),
    ]
