# Generated by Django 3.2.18 on 2023-10-11 15:08

import api.companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0043_company_document_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tech_partner_logo',
            field=models.ImageField(blank=True, null=True, upload_to=api.companies.models.tech_partner_logo_upload_path),
        ),
    ]
