# Generated by Django 3.2.20 on 2023-10-04 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0043_company_document_system'),
        ('companies', '0043_merge_0041_alter_company_logo_0042_auto_20230706_2028'),
    ]

    operations = [
    ]
