# Generated by Django 3.2.20 on 2023-10-19 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0044_company_tech_partner_logo'),
        ('companies', '0044_merge_20231004_1702'),
    ]

    operations = [
    ]
