# Generated by Django 3.2.25 on 2025-02-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0047_alter_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='show_new_commitment_flow',
            field=models.BooleanField(default=False),
        ),
    ]
