# Generated by Django 3.2.25 on 2025-05-19 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_alter_currencyrate_rate_date'),
        ('companies', '0048_company_show_new_commitment_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='base_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_companies', to='currencies.currency'),
        ),
    ]
