# Generated by Django 3.2.25 on 2025-05-29 09:36

from django.db import migrations
from django.db.transaction import atomic


def set_company_base_currency(apps, schema_editor):
    Company = apps.get_model('companies', 'Company')
    Currency = apps.get_model('currencies', 'Currency')

    usd_currencies = Currency.objects.filter(code='USD').values('id', 'company_id')

    with atomic():
        for currency in usd_currencies:
            company = Company.objects.get(id=currency['company_id'])
            company.base_currency_id = currency['id']
            company.save()


class Migration(migrations.Migration):
    dependencies = [
        ('companies', '0049_company_base_currency'),
    ]

    operations = [
        migrations.RunPython(set_company_base_currency, migrations.RunPython.noop),
    ]
