# Generated by Django 3.2.22 on 2023-12-07 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_fields.fields
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geographics', '0010_auto_20230913_1429'),
        ('companies', '0046_alter_company_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('currencies', '0002_alter_currencyrate_rate_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEmploymentRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('modified_at', models.DateTimeField(blank=True, editable=False)),
                ('salary', encrypted_fields.fields.EncryptedCharField(blank=True, default='', help_text="Position's salary, encrypted", max_length=20, null=True)),
                ('bonus', encrypted_fields.fields.EncryptedCharField(blank=True, default='', help_text='If salary has extra income as bonus', max_length=20, null=True)),
                ('job_title', models.CharField(blank=True, max_length=120, null=True)),
                ('department', models.CharField(blank=True, max_length=250, null=True)),
                ('job_band', models.CharField(blank=True, max_length=250, null=True)),
                ('hire_date', models.DateTimeField(null=True)),
                ('separation_date', models.DateTimeField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='companies.company')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('office_location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='geographics.country')),
                ('salary_currency', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='currencies.currency')),
            ],
            options={
                'verbose_name': 'historical employment record',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='EmploymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('salary', encrypted_fields.fields.EncryptedCharField(blank=True, default='', help_text="Position's salary, encrypted", max_length=20, null=True)),
                ('bonus', encrypted_fields.fields.EncryptedCharField(blank=True, default='', help_text='If salary has extra income as bonus', max_length=20, null=True)),
                ('job_title', models.CharField(blank=True, max_length=120, null=True)),
                ('department', models.CharField(blank=True, max_length=250, null=True)),
                ('job_band', models.CharField(blank=True, max_length=250, null=True)),
                ('hire_date', models.DateTimeField(null=True)),
                ('separation_date', models.DateTimeField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('office_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geographics.country')),
                ('salary_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='currencies.currency')),
            ],
            options={
                'db_table': 'employment_records',
            },
        ),
    ]
