# Generated by Django 3.2.25 on 2024-05-20 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_fields.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('currencies', '0002_alter_currencyrate_rate_date'),
        ('employment_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
            options={
                'db_table': 'company_roles',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.RemoveField(
            model_name='employmentrecord',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='employmentrecord',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='employmentrecord',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='employmentrecord',
            name='salary_currency',
        ),
        migrations.RemoveField(
            model_name='historicalemploymentrecord',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='historicalemploymentrecord',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='historicalemploymentrecord',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='historicalemploymentrecord',
            name='salary_currency',
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('annual_salary', encrypted_fields.fields.EncryptedCharField(blank=True, default='', help_text='Expected annual salary, not the current compensation', max_length=20, null=True)),
                ('target_bonus', encrypted_fields.fields.EncryptedCharField(blank=True, default='', help_text='Expected bonus, not the current bonus', max_length=20, null=True)),
                ('start_date', models.DateTimeField(help_text='Date when the employee started the role')),
                ('end_date', models.DateTimeField(help_text='Date when the employee ended the role, can be null if the employee is still in the position', null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('employment_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment_records.employmentrecord')),
                ('salary_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='currencies.currency')),
                ('title', models.ForeignKey(help_text='Role name, defined by company', on_delete=django.db.models.deletion.CASCADE, to='employment_records.companyrole')),
            ],
            options={
                'db_table': 'positions',
            },
        ),
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
            options={
                'db_table': 'office_locations',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='JobBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
            options={
                'db_table': 'job_bands',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalPosition',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('modified_at', models.DateTimeField(blank=True, editable=False)),
                ('annual_salary', encrypted_fields.fields.EncryptedCharField(blank=True, default='', help_text='Expected annual salary, not the current compensation', max_length=20, null=True)),
                ('target_bonus', encrypted_fields.fields.EncryptedCharField(blank=True, default='', help_text='Expected bonus, not the current bonus', max_length=20, null=True)),
                ('start_date', models.DateTimeField(help_text='Date when the employee started the role')),
                ('end_date', models.DateTimeField(help_text='Date when the employee ended the role, can be null if the employee is still in the position', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='companies.company')),
                ('employment_record', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employment_records.employmentrecord')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('salary_currency', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='currencies.currency')),
                ('title', models.ForeignKey(blank=True, db_constraint=False, help_text='Role name, defined by company', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employment_records.companyrole')),
            ],
            options={
                'verbose_name': 'historical position',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
            options={
                'db_table': 'departments',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='employmentrecord',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employment_records.department'),
        ),
        migrations.AlterField(
            model_name='employmentrecord',
            name='job_band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employment_records.jobband'),
        ),
        migrations.AlterField(
            model_name='employmentrecord',
            name='office_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employment_records.officelocation'),
        ),
        migrations.AlterField(
            model_name='historicalemploymentrecord',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employment_records.department'),
        ),
        migrations.AlterField(
            model_name='historicalemploymentrecord',
            name='job_band',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employment_records.jobband'),
        ),
        migrations.AlterField(
            model_name='historicalemploymentrecord',
            name='office_location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employment_records.officelocation'),
        ),
    ]
