# Generated by Django 3.2.25 on 2024-05-30 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0007_auto_20240502_1140'),
        ('documents', '0072_auto_20240510_1246'),
        ('employment_records', '0002_auto_20240520_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='employment_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='employment_records.employmentrecord'),
        ),
        migrations.CreateModel(
            name='EmployeesOnboardingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employees_onboarding_file', to='documents.document')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_users.adminuser')),
            ],
            options={
                'db_table': 'employees_onboarding_files',
            },
        ),
    ]
