# Generated by Django 3.2.25 on 2024-05-30 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
        ('employment_records', '0003_auto_20240530_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentrecord',
            name='participant_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='participants.participantprofile'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrecord',
            name='participant_profile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='participants.participantprofile'),
        ),
    ]
