# Generated by Django 3.2.25 on 2024-10-08 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employment_records', '0005_historicalcompanyrole_historicaldepartment_historicaljobband_historicalofficelocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentRecordStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10, null=True)),
                ('employment_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='employment_records.employmentrecord')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
