# Generated by Django 3.2.25 on 2025-01-23 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employment_records', '0006_employmentrecordstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentrecord',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='employment_records.employmentrecord'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrecord',
            name='manager',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employment_records.employmentrecord'),
        ),
    ]
