# Generated by Django 3.2.25 on 2025-01-29 13:04

from django.db import migrations, models
from django.db.models import Count

from api.employment_records.models import EmploymentRecord


def code(apps, schema_editor):
    EmploymentRecord = apps.get_model('employment_records', 'EmploymentRecord')
    # Get values that appear more than once in the 'email' column
    duplicate_values = EmploymentRecord.objects.values('ein').annotate(count=Count('id')).filter(count__gt=1)

    # Retrieve all objects that have these duplicate values
    duplicated_eins = EmploymentRecord.objects.filter(ein__in=[item['ein'] for item in duplicate_values])
    for i, e in enumerate(duplicated_eins):
        e.ein = str(int(e.ein) + i)
        e.save()
        

class Migration(migrations.Migration):

    dependencies = [
        ('employment_records', '0008_auto_20250128_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentrecord',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalemploymentrecord',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(code=code),
        migrations.AddConstraint(
            model_name='employmentrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('company', 'ein'), name='unique_company_ein'),
        ),
    ]
