# Generated by Django 3.2.25 on 2025-02-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment_records', '0009_auto_20250129_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentrecord',
            name='ein',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='historicalemploymentrecord',
            name='ein',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
