# Generated by Django 3.2.25 on 2025-02-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment_records', '0010_auto_20250206_0812'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employmentrecord',
            name='unique_company_ein',
        ),
        migrations.AlterField(
            model_name='historicalposition',
            name='start_date',
            field=models.DateTimeField(help_text='Date when the employee started the role', null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='start_date',
            field=models.DateTimeField(help_text='Date when the employee started the role', null=True),
        ),
        migrations.AddConstraint(
            model_name='employmentrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('ein__isnull', False), models.Q(('ein', None), _negated=True), models.Q(('ein', ''), _negated=True)), fields=('company', 'ein'), name='unique_company_ein'),
        ),
    ]
