# Generated by Django 3.2.25 on 2025-03-21 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0048_company_show_new_commitment_flow'),
        ('employment_records', '0011_auto_20250220_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFirmViewFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('filters', models.JSONField(default=list)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firm_view_filter', to='companies.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
