# Generated by Django 3.2.25 on 2025-05-19 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_alter_currency_company'),
        ('employment_records', '0012_companyfirmviewfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentrecord',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_employent_records', to='currencies.currency'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrecord',
            name='currency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='currencies.currency'),
        ),
    ]
