# Generated by Django 3.2.23 on 2024-06-12 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0046_alter_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerAPILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('request_path', models.TextField()),
                ('request_body', models.JSONField()),
                ('response_body', models.TextField(blank=True, null=True)),
                ('response_status', models.PositiveIntegerField()),
                ('request_method', models.CharField(max_length=50)),
                ('view_name', models.CharField(max_length=250)),
                ('run_time', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_api_logs', to='companies.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
