# Generated by Django 3.2.16 on 2023-05-15 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('activities', '0001_initial'), ('activities', '0002_auto_20210927_0957'), ('activities', '0003_auto_20210928_1018'), ('activities', '0004_auto_20210930_0927'), ('activities', '0005_auto_20210930_0945'), ('activities', '0006_auto_20211011_2009'), ('activities', '0007_auto_20211011_2020'), ('activities', '0008_auto_20211014_1133'), ('activities', '0009_auto_20211021_0915'), ('activities', '0010_fundactivity_distributions_since_inception'), ('activities', '0011_fundactivity_gross_share_of_nav'), ('activities', '0012_alter_fundactivity_fund_ownership'), ('activities', '0013_auto_20211110_0715'), ('activities', '0014_alter_fundactivity_fund_ownership'), ('activities', '0015_auto_20211124_0757'), ('activities', '0016_auto_20211124_0807'), ('activities', '0017_auto_20211124_1050'), ('activities', '0018_auto_20211125_0736'), ('activities', '0019_auto_20211125_0740'), ('activities', '0020_auto_20211209_1937'), ('activities', '0021_fundactivity_gross_distributions_recallable_to_date'), ('activities', '0022_auto_20220321_2332'), ('activities', '0023_alter_transactiondetail_transaction_type'), ('activities', '0024_auto_20220322_1657'), ('activities', '0025_alter_transactiondetail_effective_date'), ('activities', '0026_remove_transactiondetail_prorated_transaction_amount'), ('activities', '0027_auto_20220419_2049'), ('activities', '0028_auto_20230110_1954'), ('activities', '0029_alter_fundactivity_equity_commitment'), ('activities', '0030_alter_fundactivity_equity_commitment'), ('activities', '0031_auto_20230113_0013')]

    initial = True

    dependencies = [
        ('companies', '0003_companytoken'),
        ('companies', '0013_alter_companyuser_unique_together'),
        ('investors', '0017_fundinvestor_gross_distributions_recallable_to_date'),
        ('funds', '0024_auto_20220303_1712'),
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('transaction_date', models.DateTimeField()),
                ('investor_account_code', models.CharField(db_index=True, max_length=250)),
                ('investment_product_code', models.CharField(db_index=True, max_length=250)),
                ('loan_commitment', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('interest_balance', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('interest_repay_income', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('interest_repay_capital', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_loan_activities', to='companies.company')),
                ('interest_paid_to_date', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('loan_balance', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('leverage_ratio', models.CharField(blank=True, max_length=250, null=True)),
                ('raw_investment_product_code', models.CharField(blank=True, max_length=250, null=True)),
                ('share_class', models.CharField(blank=True, max_length=250, null=True)),
                ('loan_drawn', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('loan_repayment', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FundActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('transaction_date', models.DateTimeField()),
                ('investor_account_code', models.CharField(db_index=True, max_length=250)),
                ('investment_product_code', models.CharField(db_index=True, max_length=250)),
                ('commitment_amount', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('outstanding_commitment', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('income_distributions', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('leveraged_irr', models.FloatField(default=0)),
                ('unleveraged_irr', models.FloatField(default=0)),
                ('current_leverage_rate', models.FloatField(default=0)),
                ('initial_leverage_rate', models.FloatField(default=0)),
                ('current_interest_rate', models.FloatField(default=0)),
                ('fund_ownership', models.FloatField(default=0)),
                ('capital_called_since_last_nav', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('distributions_since_last_nav', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('unrealized_gain_loss', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('called_to_date', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_fund_activities', to='companies.company')),
                ('gain_loss', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('equity_called_to_date', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('equity_commitment', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('distributions_since_inception', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('gross_share_of_nav', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('leverage_ratio', models.CharField(blank=True, max_length=250, null=True)),
                ('raw_investment_product_code', models.CharField(blank=True, max_length=250, null=True)),
                ('share_class', models.CharField(blank=True, max_length=250, null=True)),
                ('profit_distributions', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('return_of_capital', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('distributions_recallable', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('distributions_to_employee', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('distributions_used_for_interest', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('distributions_used_for_loan', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('gross_distributions_recallable_to_date', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('partner_id', models.CharField(max_length=250)),
                ('effective_date', models.DateTimeField()),
                ('transaction_type', models.PositiveSmallIntegerField(choices=[(0, 'Unknown Transaction Type'), (1, 'Contribution Bridging Loan'), (2, 'Contribution Escrow'), (3, 'Contribution Escrow Paydown'), (4, 'Contribution Loan'), (5, 'Contribution'), (6, 'Distribution Dividend Capital Gain'), (7, 'Distribution Dividend Loan Repay Capital'), (8, 'Distribution Dividend Loan Repay Income'), (9, 'Distribution Dividend Income'), (10, 'Distribution Dividend Interest Repay Capital'), (11, 'Distribution Dividend Interest Repay Income'), (12, 'Fair Value Adjustment'), (13, 'Initial Commitment'), (14, 'Interest'), (15, 'Late Fee Charged'), (16, 'Late Fee Payment')])),
                ('actual_transaction_amount', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('prorated_transaction_amount', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_transaction_details', to='companies.company')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_transaction_details', to='funds.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_transaction_details', to='investors.investor')),
            ],
        ),
        migrations.AddConstraint(
            model_name='transactiondetail',
            constraint=models.UniqueConstraint(fields=('company', 'partner_id'), name='unique_company_detail'),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unknown Transaction Type'), (1, 'Contribution Bridging Loan'), (2, 'Contribution Escrow'), (3, 'Contribution Escrow Paydown'), (4, 'Contribution Loan'), (5, 'Contribution'), (6, 'Distribution Dividend Capital Gain'), (7, 'Distribution Dividend Loan Repay Capital'), (8, 'Distribution Dividend Loan Repay Income'), (9, 'Distribution Dividend Income'), (10, 'Distribution Dividend Interest Repay Capital'), (11, 'Distribution Dividend Interest Repay Income'), (12, 'Fair Value Adjustment'), (13, 'Initial Commitment'), (14, 'Interest'), (15, 'Late Fee Charged'), (16, 'Late Fee Payment'), (17, 'Contribution Recallable Distribution'), (18, 'Distribution Dividend Loan Repay Redemption'), (19, 'Distribution Dividend Interest Repay Redemption'), (20, 'Distribution Dividend Recallable'), (21, 'Follow on Commitment'), (22, 'Redemption')]),
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='transaction_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Draft'), (2, 'Finalized')], default=1),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unknown Transaction Type'), (1, 'Contribution Bridging Loan'), (2, 'Contribution Escrow'), (3, 'Contribution Escrow Paydown'), (4, 'Contribution Loan'), (5, 'Contribution'), (6, 'Distribution Dividend Capital Gain'), (7, 'Distribution Dividend Loan Repay Capital'), (8, 'Distribution Dividend Loan Repay Income'), (9, 'Distribution Dividend Income'), (10, 'Distribution Dividend Interest Repay Capital'), (11, 'Distribution Dividend Interest Repay Income'), (12, 'Fair Value Adjustment'), (13, 'Initial Commitment'), (14, 'Interest'), (15, 'Late Fee Charged'), (16, 'Late Fee Payment'), (17, 'Contribution Recallable Distribution'), (18, 'Distribution Dividend Loan Repay Redemption'), (19, 'Distribution Dividend Interest Repay Redemption'), (20, 'Distribution Dividend Recallable'), (21, 'Follow on Commitment'), (22, 'Redemption')], default=0),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='effective_date',
            field=models.DateField(),
        ),
        migrations.RemoveField(
            model_name='transactiondetail',
            name='prorated_transaction_amount',
        ),
        migrations.RemoveConstraint(
            model_name='transactiondetail',
            name='unique_company_detail',
        ),
        migrations.AddConstraint(
            model_name='transactiondetail',
            constraint=models.UniqueConstraint(fields=('company', 'partner_id', 'investor_id', 'fund_id', 'transaction_type', 'effective_date'), name='unique_transaction_detail'),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='called_to_date',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='capital_called_since_last_nav',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='commitment_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='distributions_recallable',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='distributions_since_inception',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='distributions_since_last_nav',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='distributions_to_employee',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='distributions_used_for_interest',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='distributions_used_for_loan',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='equity_called_to_date',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='equity_commitment',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='gain_loss',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='gross_distributions_recallable_to_date',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='gross_share_of_nav',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='income_distributions',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='outstanding_commitment',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='profit_distributions',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='return_of_capital',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='unrealized_gain_loss',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='loanactivity',
            name='interest_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='loanactivity',
            name='interest_paid_to_date',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='loanactivity',
            name='interest_repay_capital',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='loanactivity',
            name='interest_repay_income',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='loanactivity',
            name='loan_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='loanactivity',
            name='loan_commitment',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='loanactivity',
            name='loan_drawn',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='loanactivity',
            name='loan_repayment',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='actual_transaction_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='equity_commitment',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='equity_commitment',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='called_to_date',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='capital_called_since_last_nav',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='commitment_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='distributions_recallable',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='distributions_since_inception',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='distributions_since_last_nav',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='distributions_to_employee',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='distributions_used_for_interest',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='distributions_used_for_loan',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='equity_called_to_date',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='equity_commitment',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='gain_loss',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='gross_distributions_recallable_to_date',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='gross_share_of_nav',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='income_distributions',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='outstanding_commitment',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='profit_distributions',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='return_of_capital',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='unrealized_gain_loss',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='loanactivity',
            name='interest_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='loanactivity',
            name='interest_paid_to_date',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='loanactivity',
            name='interest_repay_capital',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='loanactivity',
            name='interest_repay_income',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='loanactivity',
            name='loan_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='loanactivity',
            name='loan_commitment',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='loanactivity',
            name='loan_drawn',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='loanactivity',
            name='loan_repayment',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='actual_transaction_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
    ]
