# Generated by Django 3.2.20 on 2023-07-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0031_auto_20230113_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundactivity',
            name='investment_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='loanactivity',
            name='investment_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
