# Generated by Django 3.2.18 on 2023-07-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_records', '0049_auto_20230523_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkycrecord',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
