# Generated by Django 3.2.18 on 2023-07-26 07:13

from django.db import migrations

from api.workflows.models import WorkFlow


def mark_approved_kyc_records(apps, schema_editor):
    Application = apps.get_model('applications', 'Application')
    for application in Application.objects.all():
        if not application.workflow or not application.kyc_record:
            continue

        if application.workflow.child_workflows.filter(
                module=WorkFlow.WorkFlowModuleChoices.AML_KYC.value,
                is_completed=True
        ).exists():
            application.kyc_record.approved = True
            application.kyc_record.save()


def unmark_approved_kyc_records(apps, schema_editor):
    KycRecord = apps.get_model('kyc_records', 'KycRecord')
    KycRecord.objects.all().update(approved=False)


class Migration(migrations.Migration):
    dependencies = [
        ('kyc_records', '0050_auto_20230726_0648'),
    ]

    operations = [
        migrations.RunPython(mark_approved_kyc_records, reverse_code=unmark_approved_kyc_records)
    ]
