# Generated by Django 3.2.21 on 2023-10-04 13:05

from django.db import migrations
from django_q.models import Schedule


def create_expiration_email_schedule(apps, schema_editor):
    Schedule.objects.create(
        func='api.kyc_records.utils.email_expiration_report',
        kwargs='company_name="lasalle"',
        schedule_type=Schedule.CRON,
        cron='0 0 1 * *'
    )


def delete_expiration_email_schedule(apps, schema_editor):
    Schedule.objects.filter(
        func='api.kyc_records.utils.email_expiration_report',
        kwargs='company_name="lasalle"',
        schedule_type=Schedule.CRON,
        cron='0 0 1 * *'
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('django_q', '0014_schedule_cluster'),
        ('kyc_records', '0051_auto_20230726_0713'),
    ]

    operations = [
        migrations.RunPython(create_expiration_email_schedule, reverse_code=delete_expiration_email_schedule)
    ]
