# Generated by Django 3.2.23 on 2023-11-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_records', '0052_auto_20231004_1305'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='kycrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), models.Q(('kyc_investor_type', 2), _negated=True)), fields=('company', 'user', 'workflow', 'kyc_investor_type'), name='unique_kyc_validation'),
        ),
    ]
