# Generated by Django 3.2.18 on 2023-05-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_merge_20230323_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalretailuser',
            name='invite_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Invited'), (2, 'Accepted Invite')], null=True),
        ),
        migrations.AddField(
            model_name='retailuser',
            name='invite_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Invited'), (2, 'Accepted Invite')], null=True),
        ),
    ]
