# Generated by Django 3.2.23 on 2024-03-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20230524_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalretailuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='historicalretailuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='retailuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='retailuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='full name'),
        ),
    ]
