# Generated by Django 3.2.19 on 2024-06-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20240311_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalretailuser',
            name='is_advisor',
            field=models.BooleanField(default=False, verbose_name='is advisor'),
        ),
        migrations.AddField(
            model_name='retailuser',
            name='is_advisor',
            field=models.BooleanField(default=False, verbose_name='is advisor'),
        ),
    ]
