# Generated by Django 3.2.25 on 2024-10-14 12:11
from api.users.constants import CARRY_REVIEWER
from django.contrib.auth.models import Group
from django.db import migrations


def create_carry_reveiwer_groups(apps, schema_editor):
    Group.objects.get_or_create(name=CARRY_REVIEWER)


def delete_carry_reveiwer_groups(apps, schema_editor):
    Group.objects.filter(name=CARRY_REVIEWER).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20240624_1013'),
    ]

    operations = [
        migrations.RunPython(create_carry_reveiwer_groups, reverse_code=delete_carry_reveiwer_groups),
    ]
