# Generated by Django 3.2.16 on 2023-05-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0042_merge_20230512_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userapplicationstate',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveConstraint(
            model_name='userapplicationstate',
            name='unique_user_fund_validation',
        ),
        migrations.AddField(
            model_name='application',
            name='is_transferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='is_transferred',
            field=models.BooleanField(default=False),
        ),
    ]
