# Generated by Django 3.2.18 on 2023-05-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0042_merge_20230512_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='has_submitted_banking_details',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='has_submitted_banking_details',
            field=models.BooleanField(default=False),
        ),
    ]
