# Generated by Django 3.2.16 on 2023-05-31 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_remove_transfer_application'),
        ('applications', '0043_auto_20230529_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='state',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_application', to='applications.userapplicationstate'),
        ),
        migrations.AddField(
            model_name='application',
            name='transfer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_application', to='transfers.transfer'),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='state',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='applications.userapplicationstate'),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='transfer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transfers.transfer'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('is_transferred', False)), fields=('user', 'fund'), name='unique_user_fund_validation'),
        ),
    ]
