# Generated by Django 3.2.18 on 2023-05-30 13:39

from django.db import migrations


def set_banking_details_submitted_for_applications(apps, schema):
    Application = apps.get_model('applications', 'Application')
    Application.objects.filter(payment_detail__isnull=False).update(has_submitted_banking_details=True)


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0043_auto_20230530_1339'),
    ]

    operations = [
        migrations.RunPython(set_banking_details_submitted_for_applications, reverse_code=migrations.RunPython.noop)
    ]
