# Generated by Django 3.2.16 on 2023-05-31 10:40

from django.db import migrations


def fill_user_application_state_in_application(apps, schema_editor):
    Application = apps.get_model('applications', 'Application')
    UserApplicationState = apps.get_model('applications', 'UserApplicationState')

    applications = []

    for application in Application.objects.all():
        state = UserApplicationState.objects.filter(
            user=application.user,
            fund=application.fund
        ).first()

        application.state = state
        applications.append(application)

    Application.objects.bulk_update(applications, ['state'])


def empty_user_application_state_in_application(apps, schema_editor):
    Application = apps.get_model('applications', 'Application')
    Application.objects.update(state=None)


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0044_auto_20230531_0856'),
    ]

    operations = [
        migrations.RunPython(fill_user_application_state_in_application, empty_user_application_state_in_application),
    ]
