# Generated by Django 3.2.16 on 2023-06-21 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0003_remove_transfer_equity'),
        ('applications', '0045_auto_20230531_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='state',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_application', to='applications.userapplicationstate'),
        ),
        migrations.AlterField(
            model_name='application',
            name='transfer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_application', to='transfers.transfer'),
        ),
    ]
