# Generated by Django 3.2.20 on 2023-07-20 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0044_auto_20230530_1339'),
        ('applications', '0046_auto_20230621_1252'),
    ]

    operations = [
    ]
