# Generated by Django 3.2.18 on 2023-07-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0047_merge_0044_auto_20230530_1339_0046_auto_20230621_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='aml_kyc_tax_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='aml_kyc_tax_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
