# Generated by Django 3.2.21 on 2023-11-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0049_auto_20230831_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='gp_signing_completed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='gp_signing_completed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
