# Generated by Django 3.2.23 on 2023-11-24 08:03

from django.db import migrations

from api.agreements.selectors.application_agreements import all_agreements_gp_signed
from api.applications.models import Application


def set_gp_signing_completed_date(apps, schema_editor):
    ApplicationModel = apps.get_model('applications', 'Application')

    for application in ApplicationModel.objects.filter(status=Application.Status.APPROVED.value):
        if not all_agreements_gp_signed(application):
            continue

        last_approved_document = application.application_agreements.filter(gp_signing_complete=True).order_by(
            '-modified_at').first()
        if last_approved_document:
            application.gp_signing_completed_at = last_approved_document.modified_at
            application.save()


def unset_gp_signing_completed_date(apps, schema_editor):
    ApplicationModel = apps.get_model('applications', 'Application')
    ApplicationModel.objects.update(gp_signing_completed_at=None)


class Migration(migrations.Migration):
    dependencies = [
        ('applications', '0050_auto_20231108_1127'),
    ]

    operations = [
        migrations.RunPython(set_gp_signing_completed_date, reverse_code=unset_gp_signing_completed_date)
    ]
