# Generated by Django 3.2.25 on 2024-12-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0051_auto_20231124_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='disable_cashless_commitment',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='disable_cashless_commitment',
            field=models.BooleanField(null=True),
        ),
    ]
