# Generated by Django 3.2.25 on 2025-02-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0052_auto_20241218_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='aml_kyc_pre_document_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='aml_kyc_pre_document_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
