# Generated by Django 3.2.16 on 2023-05-29 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0043_auto_20230529_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('equity', models.DecimalField(decimal_places=3, max_digits=13)),
                ('loan_date', models.DateField(blank=True, null=True)),
                ('loan_balance', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('interest_date', models.DateField(blank=True, null=True)),
                ('interest_balance', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer', to='applications.application')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
