# Generated by Django 3.2.16 on 2023-06-13 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_remove_transfer_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='equity',
        ),
    ]
