# Generated by Django 3.2.18 on 2023-06-09 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0045_auto_20230531_1040'),
        ('eligibility_criteria', '0061_auto_20230510_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilitycriteriaresponse',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_eligibility_responses', to='applications.application'),
        ),
    ]
