# Generated by Django 3.2.18 on 2023-06-22 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0006_auto_20230103_1142'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflows', '0033_alter_workflow_managers'),
        ('funds', '0062_auto_20230616_0715'),
        ('eligibility_criteria', '0062_eligibilitycriteriaresponse_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFundEligibilityCriteria',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('modified_at', models.DateTimeField(blank=True, editable=False)),
                ('investor_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Individual'), (2, 'Entity')], null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Draft'), (2, 'Pending Approval'), (3, 'Approved'), (4, 'Published')], default=1)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('custom_expression', models.JSONField(null=True)),
                ('expression_override', models.TextField(blank=True, null=True)),
                ('smart_canvas_payload', models.JSONField(null=True)),
                ('is_smart_criteria', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='admin_users.adminuser')),
                ('fund', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='funds.fund')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflows.workflow')),
            ],
            options={
                'verbose_name': 'historical fund eligibility criteria',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
