# Generated by Django 3.2.20 on 2023-08-28 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0062_alter_block_logo'),
        ('eligibility_criteria', '0063_historicalfundeligibilitycriteria'),
    ]

    operations = [
    ]
