# Generated by Django 3.2.18 on 2023-08-22 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0042_auto_20230706_2028'),
        ('eligibility_criteria', '0063_historicalfundeligibilitycriteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsmartblock',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CustomSmartBlockTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_multiple_selection_enabled', models.BooleanField(blank=True, default=True, null=True)),
                ('custom_fields', models.JSONField(default=list)),
                ('deleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_template', to='companies.company')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='customsmartblock',
            name='source_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eligibility_criteria.customsmartblocktemplate'),
        ),
        migrations.AddConstraint(
            model_name='customsmartblocktemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('company', 'slug'), name='unique_company_template_title'),
        ),
    ]
