# Generated by Django 3.2.18 on 2023-08-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0064_auto_20230822_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customsmartblocktemplate',
            options={'ordering': ('title',)},
        ),
        migrations.AlterField(
            model_name='customsmartblocktemplate',
            name='title',
            field=models.TextField(max_length=250),
        ),
    ]
