# Generated by Django 3.2.21 on 2023-09-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0065_auto_20230830_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvestmentamount',
            name='final_leverage_ratio',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='investmentamount',
            name='final_leverage_ratio',
            field=models.FloatField(default=None),
        ),
    ]
