# Generated by Django 3.2.20 on 2023-10-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0065_auto_20230830_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvestmentamount',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='investmentamount',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
    ]
