# Generated by Django 3.2.21 on 2023-10-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0066_auto_20230929_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvestmentamount',
            name='final_leverage_ratio',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='investmentamount',
            name='final_leverage_ratio',
            field=models.FloatField(default=None, null=True),
        ),
    ]
