# Generated by Django 3.2.20 on 2023-10-04 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0064_merge_20230828_1848'),
        ('eligibility_criteria', '0067_auto_20231002_0918'),
    ]

    operations = [
    ]
