# Generated by Django 3.2.20 on 2023-10-04 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0066_auto_20231002_1806'),
        ('eligibility_criteria', '0067_auto_20231002_0918'),
    ]

    operations = [
    ]
