# Generated by Django 3.2.20 on 2023-10-12 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0068_merge_0066_auto_20231002_1806_0067_auto_20231002_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalinvestmentamount',
            old_name='description',
            new_name='leverage_option_description',
        ),
        migrations.RenameField(
            model_name='investmentamount',
            old_name='description',
            new_name='leverage_option_description',
        ),
    ]
