# Generated by Django 3.2.22 on 2023-10-30 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0068_merge_20231004_1702'),
        ('eligibility_criteria', '0069_auto_20231012_1924'),
    ]

    operations = [
    ]
