# Generated by Django 3.2.23 on 2023-11-29 10:29

import api.eligibility_criteria.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0070_merge_20231030_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteriablockresponse',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='criteriablockresponse',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('criteria_response', 'block'), name='unique_criteria_block_response_block'),
        ),
    ]
