# Generated by Django 3.2.23 on 2023-11-29 11:07

import api.eligibility_criteria.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0071_auto_20231129_1029'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='eligibilitycriteriaresponse',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('criteria', 'response_by', 'application'), name='unique_criteria_response_user_application_criteria'),
        ),
    ]
