# Generated by Django 3.2.19 on 2024-06-10 12:01

import api.eligibility_criteria.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0073_alter_block_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvestmentamount',
            name='levered_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='historicalinvestmentamount',
            name='unlevered_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='investmentamount',
            name='levered_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='investmentamount',
            name='unlevered_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
    ]
