# Generated by Django 3.2.19 on 2024-06-12 08:53

import api.eligibility_criteria.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0074_auto_20240610_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvestmentamount',
            name='max_levered_commitment_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='investmentamount',
            name='max_levered_commitment_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
    ]
