# Generated by Django 3.2.25 on 2024-12-23 10:20

from django.db import migrations


def update_final_leverage_description(apps, schema_editor):
    InvestmentAmount = apps.get_model('eligibility_criteria', 'InvestmentAmount')
    for investment_amount in InvestmentAmount.objects.all():
        investment_amount.final_leverage_option_description = investment_amount.leverage_option_description
        investment_amount.save()


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0076_auto_20241223_1016'),
    ]

    operations = [
        migrations.RunPython(
            update_final_leverage_description,
            reverse_code=migrations.RunPython.noop
        )
    ]
