# Generated by Django 3.2.25 on 2025-01-15 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0076_alter_block_logo'),
        ('eligibility_criteria', '0077_auto_20241223_1020'),
    ]

    operations = [
    ]
