# Generated by Django 3.2.25 on 2025-01-22 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0076_auto_20241218_0917'),
        ('eligibility_criteria', '0078_merge_0076_alter_block_logo_0077_auto_20241223_1020'),
    ]

    operations = [
    ]
