# Generated by Django 3.2.25 on 2025-01-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0079_merge_20250122_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvestmentamount',
            name='final_leverage_option_description',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='historicalinvestmentamount',
            name='leverage_option_description',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='investmentamount',
            name='final_leverage_option_description',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='investmentamount',
            name='leverage_option_description',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
