# Generated by Django 3.2.25 on 2025-01-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0079_merge_20250122_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsmartblockfield',
            name='is_nested_fields_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customsmartblockfield',
            name='is_text_explanation_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customsmartblockfield',
            name='nested_fields',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='customsmartblockfield',
            name='text_explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
