# Generated by Django 3.2.25 on 2025-02-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0080_auto_20250129_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvestmentamount',
            name='max_leverage_percentage',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='investmentamount',
            name='max_leverage_percentage',
            field=models.FloatField(default=None, null=True),
        ),
    ]
