# Generated by Django 3.2.25 on 2025-02-07 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0080_auto_20250128_1210'),
        ('eligibility_criteria', '0080_auto_20250129_0750'),
    ]

    operations = [
    ]
