# Generated by Django 3.2.25 on 2025-02-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0080_auto_20250129_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvestmentamount',
            name='leverage_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name='investmentamount',
            name='leverage_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13),
        ),
    ]
