# Generated by Django 3.2.25 on 2025-02-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0081_auto_20250210_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvestmentamount',
            name='leverage_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='investmentamount',
            name='leverage_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
    ]
