# Generated by Django 3.2.25 on 2025-02-07 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0081_merge_0080_auto_20250128_1210_0080_auto_20250129_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customsmartblockfield',
            name='text_explanation',
        ),
    ]
