# Generated by Django 3.2.25 on 2025-02-14 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0081_auto_20250210_1152'),
        ('eligibility_criteria', '0082_auto_20250210_1214'),
    ]

    operations = [
    ]
