# Generated by Django 3.2.25 on 2025-02-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0082_remove_customsmartblockfield_text_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsmartblockfield',
            name='text_explanations',
            field=models.JSONField(default=list),
        ),
    ]
