# Generated by Django 3.2.25 on 2025-02-07 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0083_customsmartblockfield_text_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customsmartblockfield',
            name='nested_fields',
        ),
        migrations.AddField(
            model_name='customsmartblockfield',
            name='parent_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_fields', to='eligibility_criteria.customsmartblockfield'),
        ),
    ]
