# Generated by Django 3.2.25 on 2025-02-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0083_merge_0081_auto_20250210_1152_0082_auto_20250210_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvestmentamount',
            name='final_cashless_commitment',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='investmentamount',
            name='final_cashless_commitment',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
    ]
