# Generated by Django 3.2.25 on 2025-03-12 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0084_auto_20250207_1219'),
        ('eligibility_criteria', '0084_auto_20250214_0803'),
    ]

    operations = [
    ]
