# Generated by Django 3.2.25 on 2025-03-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0085_merge_0084_auto_20250207_1219_0084_auto_20250214_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customsmartblockfield',
            name='text_explanations',
        ),
        migrations.AddField(
            model_name='customsmartblockfield',
            name='text_explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
