# Generated by Django 3.2.25 on 2025-05-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0086_auto_20250312_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsmartblockfield',
            name='nested_field_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
