# Generated by Django 3.2.18 on 2023-07-18 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0032_merge_20230512_1350'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='workflow',
            managers=[
            ],
        ),
    ]
