# Generated by Django 3.2.25 on 2024-10-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0033_alter_workflow_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='module',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Eligibility'), (2, 'Indication Of Interest'), (3, 'AML/KYC'), (4, 'User On-boarding'), (5, 'Tax Record'), (6, 'Agreements'), (7, 'Allocation'), (8, 'GP Signing'), (9, 'Internal Tax Review'), (10, 'Capital Call'), (11, 'Distribution Notice'), (12, 'Carry Plan')], db_index=True),
        ),
    ]
