# Generated by Django 3.2.25 on 2025-02-13 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0047_alter_company_logo'),
        ('workflows', '0034_alter_workflow_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='module',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Eligibility'), (2, 'Indication Of Interest'), (3, 'AML/KYC'), (4, 'User On-boarding'), (5, 'Tax Record'), (6, 'Agreements'), (7, 'Allocation'), (8, 'GP Signing'), (9, 'Internal Tax Review'), (10, 'Capital Call'), (11, 'Distribution Notice'), (12, 'Carry Plan'), (13, 'Pre Document Signing')], db_index=True),
        ),
        migrations.CreateModel(
            name='CompanyWorkFlowConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('require_eligibility_approval', models.BooleanField(default=False)),
                ('require_allocation_approval', models.BooleanField(default=False)),
                ('require_kyc_approval', models.BooleanField(default=True)),
                ('require_tax_approval', models.BooleanField(default=False)),
                ('require_pre_document_signing_approval', models.BooleanField(default=True)),
                ('require_agreement_approval', models.BooleanField(default=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_workflow_config', to='companies.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
