# Generated by Django 3.2.20 on 2023-07-28 18:41
import logging

from django.db import migrations, models

logger = logging.getLogger()


def adjust_share_class(fund_activity, fund_model, investor_model, fund_investor_model):
    investor_qs = investor_model.objects.filter(investor_account_code=fund_activity.investor_account_code)
    if investor_qs.exists():
        investor = investor_qs.first()  # there should be only one
        fund_qs = fund_model.objects.filter(investment_product_code=fund_activity.investment_product_code, company=fund_activity.company)
        if fund_qs.exists():
            fund = fund_qs.first()  # there should be only one
            investment = fund_investor_model.objects.filter(investor=investor, fund=fund).first()  # there should be only one
            investment.share_class = fund_activity.share_class
            investment.save()
        else:
            logger.info(f"No fund for investment_product_code: {fund_activity.investment_product_code} and company: {fund_activity.company.id}")
    else:
        logger.warning(f"No investor for investor_account_code: {fund_activity.investor_account_code}")


def share_class_in_investor(apps, schema_editor):
    FundActivity = apps.get_model('activities', 'FundActivity')
    LoanActivities = apps.get_model('activities', 'LoanActivity')
    Investor = apps.get_model('investors', 'Investor')
    FundInvestor = apps.get_model('investors', 'FundInvestor')
    Fund = apps.get_model('funds', 'Fund')
    fund_activities_with_share_class = FundActivity.objects.filter(share_class__isnull=False)
    loan_activities_with_share_class = LoanActivities.objects.filter(share_class__isnull=False)
    for fund_activity in fund_activities_with_share_class.all():
        adjust_share_class(fund_activity, Fund, Investor, FundInvestor)

    for loan_activity in loan_activities_with_share_class.all():
        fund_activity = FundActivity.objects.filter(
            company=loan_activity.company,
            investment_product_code=loan_activity.investment_product_code,
            share_class=loan_activity.share_class,
            investor_account_code=loan_activity.investor_account_code
        ).latest('transaction_date')
        adjust_share_class(fund_activity, Fund, Investor, FundInvestor)


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0062_auto_20230616_0715'),
        ('investors', '0027_auto_20230113_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundinvestor',
            name='share_class',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='fundinvestor',
            unique_together={('fund', 'investor', 'share_class')},
        ),
        migrations.RunPython(code=share_class_in_investor, reverse_code=lambda _, __: None),
    ]
