# Generated by Django 3.2.20 on 2023-07-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0062_auto_20230616_0715'),
        ('investors', '0028_auto_20230728_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundinvestor',
            name='investment_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='fundinvestor',
            unique_together={('fund', 'investor', 'share_class', 'investment_id')},
        ),
    ]
