# Generated by Django 3.2.18 on 2023-08-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0029_auto_20230731_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvestor',
            name='partner_id',
            field=models.CharField(db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='partner_id',
            field=models.CharField(db_index=True, max_length=250, null=True, unique=True),
        ),
    ]
