# Generated by Django 3.2.20 on 2023-09-12 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0064_historicalfund'),
        ('investors', '0030_auto_20230825_1304'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fundinvestor',
            unique_together={('fund', 'investor', 'investment_id')},
        ),
    ]
