# Generated by Django 3.2.19 on 2024-03-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0072_auto_20240129_1041'),
        ('investors', '0031_alter_fundinvestor_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fundinvestor',
            unique_together={('fund', 'investor', 'investment_id', 'latest_transaction_date')},
        ),
    ]
