# Generated by Django 3.2.19 on 2024-06-24 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0046_alter_company_logo'),
        ('investors', '0032_alter_fundinvestor_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorAdvisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_advisor_investors', to='companies.companyuser')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_investor_advisors', to='companies.companyuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
