# Generated by Django 3.2.19 on 2024-06-26 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0046_alter_company_logo'),
        ('investors', '0033_investoradvisor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='investoradvisor',
            unique_together={('advisor', 'investor')},
        ),
    ]
