# Generated by Django 3.2.25 on 2024-10-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0034_alter_investoradvisor_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundinvestor',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='fundinvestor',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='fundinvestor',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('fund', 'investor', 'investment_id', 'latest_transaction_date'), name='unique_fund_investment'),
        ),
    ]
