# Generated by Django 3.2.25 on 2025-02-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0035_auto_20241024_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundinvestor',
            name='approved_for_recycling',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='fundinvestor',
            name='drop_leverage_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundinvestor',
            name='drop_loan_to_value',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='fundinvestor',
            name='never_will_be_called',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='fundinvestor',
            name='offset_called',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='fundinvestor',
            name='offset_commitment',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='fundinvestor',
            name='total_commitment',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='fundinvestor',
            name='total_commitment_including_recycling',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='fundinvestor',
            name='unfunded_commitment',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
    ]
