# Generated by Django 3.2.25 on 2025-05-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0036_auto_20250217_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundinvestor',
            name='management_fee',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='fundinvestor',
            name='unfunded_capital_commitment',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
    ]
