# Generated by Django 3.2.25 on 2025-05-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0037_auto_20250515_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuserinvestor',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Manager'), (2, 'Primary User'), (3, 'Secondary User')], default=1),
        ),
    ]
