# Generated by Django 3.2.25 on 2025-05-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0037_auto_20250515_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundinvestor',
            name='cash_called',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='fundinvestor',
            name='loan_called',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
    ]
