# Generated by Django 3.2.25 on 2025-05-29 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0038_alter_companyuserinvestor_role'),
        ('investors', '0038_auto_20250520_1148'),
    ]

    operations = [
    ]
