# Generated by Django 3.2.13 on 2022-08-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_alter_companyuser_department'),
        ('documents', '0048_funddocument_gp_signer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='partner_id',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('company_id', 'partner_id')},
        ),
    ]
