# Generated by Django 3.2.18 on 2023-07-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0064_auto_20230320_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='funddocument',
            name='require_acknowledgement',
            field=models.BooleanField(default=True),
        ),
    ]
