# Generated by Django 3.2.16 on 2023-06-30 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0049_auto_20220805_1317'),
        ('documents', '0064_auto_20230320_1138'),
    ]

    operations = [
    ]
