# Generated by Django 3.2.18 on 2023-07-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0065_funddocument_require_acknowledgement'),
    ]

    operations = [
        migrations.AddField(
            model_name='funddocument',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investordocument',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
