# Generated by Django 3.2.22 on 2023-11-16 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0065_merge_0049_auto_20220805_1317_0064_auto_20230320_1138'),
        ('documents', '0066_auto_20230720_1236'),
    ]

    operations = [
    ]
