# Generated by Django 3.2.22 on 2023-12-18 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0067_historicalkycdocument'),
        ('documents', '0067_merge_20231116_1249'),
    ]

    operations = [
    ]
