# Generated by Django 3.2.23 on 2024-05-10 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0071_auto_20240425_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='funddocument',
            name='is_replaced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='funddocument',
            name='replaced_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.funddocument'),
        ),
    ]
