# Generated by Django 3.2.25 on 2024-06-18 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0007_auto_20240502_1140'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funds', '0077_auto_20240610_1028'),
        ('documents', '0072_auto_20240510_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFundDocument',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('modified_at', models.DateTimeField(blank=True, editable=False)),
                ('is_replaced', models.BooleanField(default=False)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('require_signature', models.BooleanField(default=False)),
                ('require_gp_signature', models.BooleanField(default=False)),
                ('require_acknowledgement', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('document', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='documents.document')),
                ('fund', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='funds.fund')),
                ('gp_signer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='admin_users.adminuser')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('replaced_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='documents.funddocument')),
            ],
            options={
                'verbose_name': 'historical fund document',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
