# Generated by Django 3.2.16 on 2023-04-03 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0037_merge_20230323_1336'),
        ('funds', '0054_fund_enable_internal_tax_flow'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('page', models.CharField(choices=[('investor_dashboard', 'Investor Dashboard'), ('investment_detail_page', 'Investment Detail Page')], max_length=50)),
                ('page_value', models.JSONField(default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funds.fund')),
            ],
            options={
                'unique_together': {('company', 'page')},
            },
        ),
    ]
