# Generated by Django 3.2.16 on 2023-04-05 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_configs', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pageconfig',
            unique_together=set(),
        ),
    ]
