# Generated by Django 3.2.23 on 2024-04-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_configs', '0004_auto_20240404_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpageconfig',
            name='page',
            field=models.CharField(choices=[('investor_dashboard', 'Investor Dashboard'), ('investment_detail_page', 'Investment Detail Page'), ('notice_considerations', 'Notice Considerations'), ('notice_considerations_firm_detail', 'Notice Considerations Firm Detail')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pageconfig',
            name='page',
            field=models.CharField(choices=[('investor_dashboard', 'Investor Dashboard'), ('investment_detail_page', 'Investment Detail Page'), ('notice_considerations', 'Notice Considerations'), ('notice_considerations_firm_detail', 'Notice Considerations Firm Detail')], max_length=50),
        ),
    ]
