# Generated by Django 3.2.25 on 2024-10-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_configs', '0006_auto_20240521_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpageconfig',
            name='page',
            field=models.CharField(choices=[('investor_dashboard', 'Investor Dashboard'), ('investment_detail_page', 'Investment Detail Page'), ('notice_considerations', 'Notice Considerations'), ('notice_considerations_firm_detail', 'Notice Considerations Firm Detail'), ('compensation_view', 'Compensation View'), ('carry_config', 'Carry Config')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pageconfig',
            name='page',
            field=models.CharField(choices=[('investor_dashboard', 'Investor Dashboard'), ('investment_detail_page', 'Investment Detail Page'), ('notice_considerations', 'Notice Considerations'), ('notice_considerations_firm_detail', 'Notice Considerations Firm Detail'), ('compensation_view', 'Compensation View'), ('carry_config', 'Carry Config')], max_length=50),
        ),
    ]
