# Generated by Django 3.2.25 on 2025-04-21 10:14

from django.db import migrations

def add_custom_chart_total(apps, schema_editor):
    PageConfig = apps.get_model('page_configs', 'PageConfig')
    for page_config in PageConfig.objects.filter(
        company__name__istartswith='riverside',
        page='investor_dashboard'
    ):
        page_value = page_config.page_value
        page_value['use_custom_chart_total'] = True
        page_config.page_value = page_value
        page_config.save()


class Migration(migrations.Migration):

    dependencies = [
        ('page_configs', '0008_customtextconfig_historicalcustomtextconfig'),
    ]

    operations = [
        migrations.RunPython(add_custom_chart_total, migrations.RunPython.noop),
    ]

