# Generated by Django 3.2.25 on 2025-05-19 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0049_company_base_currency'),
        ('currencies', '0002_alter_currencyrate_rate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_currency', to='companies.company'),
        ),
    ]
