# Generated by Django 3.2.18 on 2023-09-13 14:29

from django.db import migrations


def add_russia_to_countries(apps, schema_editor):
    Country = apps.get_model('geographics', 'Country')
    Country.objects.create(
        name="Russian Federation",
        iso_code="RU"
    )


class Migration(migrations.Migration):
    dependencies = [
        ('geographics', '0009_address'),
    ]

    operations = [
        migrations.RunPython(add_russia_to_countries),
    ]
