PARTICIPANT_COLUMN = 'Participant'
GRANT_DATE_COLUMN = 'Grant Date'
VEHICLE_COLUMN = 'Vehicle'
SHARE_CLASS_COLUMN = 'Share Class'
VESTING_START_DATE_COLUMN = 'Vesting Start Date'
VESTED_COLUMN = 'Vested'
UNVESTED_COLUMN = 'Unvested'
TOTAL_COLUMN = 'Total'
SOURCE_COLUMN = 'Source'
CARRY_PLAN_COLUMN = 'Carry Plan Name'
ESTIMATED_VALUE_AS_OF_COLUMN = "Estimated Value As Of"
ESTIMATED_VALUE_VESTED_COLUMN = "Vested Estimated Value"
ESTIMATED_VALUE_UNVESTED_COLUMN = "Unvested Estimated Value" 
ESTIMATED_VALUE_COLUMN = "Estimated Value"
FAIR_MARKET_VALUE_AS_OF_COLUMN = "Fair Market Value As Of"	
FAIR_MARKET_VALUE_COLUMN = "Fair Market Value"	
VESTED_FAIR_MARKET_VALUE_COLUMN = "Vested Fair Market Value"
UNVESTED_FAIR_MARKET_VALUE_COLUMN = "Unvested Fair Market Value"
DISTRIBUTIONS_COLUMN = "Distributions"
VESTING_SCHEDULE_COLUMN ="Vesting Schedule"
POINTS_COLUMN = "Points"
SUBPOOL_COLUMN = "Carry Pool Name"
PARTICIPANT_NAME_COLUMN = 'Participant Name'

COLUMN_ORDER = (
    PARTICIPANT_COLUMN,
    GRANT_DATE_COLUMN,
    VEHICLE_COLUMN,
    SHARE_CLASS_COLUMN,
    VESTING_START_DATE_COLUMN,
    VESTED_COLUMN,
    UNVESTED_COLUMN,
    TOTAL_COLUMN
)

COLUMN_MAPPING = {
    'participant': PARTICIPANT_COLUMN,
    'grant_date': GRANT_DATE_COLUMN,
    'vehicle': VEHICLE_COLUMN,
    'share_class': SHARE_CLASS_COLUMN,
    'vesting_start_date': VESTING_START_DATE_COLUMN,
    'vested': VESTED_COLUMN,
    'unvested': UNVESTED_COLUMN,
    'total': TOTAL_COLUMN
}

ALLOCATIONS_EXPORT_COLUMN_MAPPING = {
    'participant': PARTICIPANT_COLUMN,
    'grant_date': GRANT_DATE_COLUMN,
    'vehicle': VEHICLE_COLUMN,
    'share_class': SHARE_CLASS_COLUMN,
    'vesting_start_date': VESTING_START_DATE_COLUMN,
    'vested': VESTED_COLUMN,
    'unvested': UNVESTED_COLUMN,
    'points': POINTS_COLUMN,
    'estimated_value': ESTIMATED_VALUE_COLUMN,
    'estimated_value_vested': ESTIMATED_VALUE_VESTED_COLUMN,
    'estimated_value_unvested': ESTIMATED_VALUE_UNVESTED_COLUMN,
    'fair_market_value': FAIR_MARKET_VALUE_COLUMN,
    'vested_fair_market_value': VESTED_FAIR_MARKET_VALUE_COLUMN,
    'unvested_fair_market_value': UNVESTED_FAIR_MARKET_VALUE_COLUMN,
    'estimated_value_as_of': ESTIMATED_VALUE_AS_OF_COLUMN,
    'fair_market_value_as_of': FAIR_MARKET_VALUE_AS_OF_COLUMN,
    'distributions': DISTRIBUTIONS_COLUMN,
    'vesting_schedule': VESTING_SCHEDULE_COLUMN,
    'carry_plan_name': CARRY_PLAN_COLUMN,
    'source': SOURCE_COLUMN,
    'sub_pool_name': SUBPOOL_COLUMN,
}


ALLOCATIONS_EXPORT_COLUMN_ORDER = (
    GRANT_DATE_COLUMN,
    SOURCE_COLUMN,
    CARRY_PLAN_COLUMN,
    SUBPOOL_COLUMN,
    VEHICLE_COLUMN,
    SHARE_CLASS_COLUMN,
    PARTICIPANT_COLUMN,
    VESTING_SCHEDULE_COLUMN,
    VESTING_START_DATE_COLUMN,
    POINTS_COLUMN,
    VESTED_COLUMN,
    UNVESTED_COLUMN,
    ESTIMATED_VALUE_AS_OF_COLUMN,
    ESTIMATED_VALUE_COLUMN,
    ESTIMATED_VALUE_VESTED_COLUMN,
    ESTIMATED_VALUE_UNVESTED_COLUMN,
    FAIR_MARKET_VALUE_AS_OF_COLUMN,
    FAIR_MARKET_VALUE_COLUMN,
    VESTED_FAIR_MARKET_VALUE_COLUMN,
    UNVESTED_FAIR_MARKET_VALUE_COLUMN,
    DISTRIBUTIONS_COLUMN,
)