# Generated by Django 3.2.18 on 2023-07-10 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0006_auto_20230103_1142'),
        ('carry_pools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundcarrypool',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pools', to='admin_users.adminuser'),
        ),
        migrations.AddField(
            model_name='historicalfundcarrypool',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='admin_users.adminuser'),
        ),
    ]
