# Generated by Django 3.2.18 on 2023-07-21 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0002_auto_20230710_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundcarrypool',
            name='participants',
        ),
        migrations.DeleteModel(
            name='PoolParticipant',
        ),
    ]
