# Generated by Django 3.2.18 on 2023-07-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0003_auto_20230721_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundcarrypool',
            name='participants',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='historicalfundcarrypool',
            name='participants',
            field=models.JSONField(default=list),
        ),
    ]
