# Generated by Django 3.2.16 on 2023-08-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0004_auto_20230721_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(1, 'Draft'), (2, 'Under Review'), (3, 'Approved'), (4, 'Awaiting Participant Signature'), (5, 'Signed by Participant'), (6, 'Signed by GP'), (7, 'Forfeited')], default='Draft', max_length=50)),
                ('vesting_schedule', models.CharField(default='5 years straight', max_length=120)),
                ('grant_date', models.DateTimeField()),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[(1, 'Create'), (2, 'Delete'), (3, 'Forfeit'), (4, 'Dilute')], max_length=50)),
                ('pool_or_participant', models.JSONField()),
                ('fund_external_id', models.CharField(max_length=120)),
                ('base_pool_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('parent_pool_id', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
