# Generated by Django 3.2.16 on 2023-08-16 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0005_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allocation',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Draft'), (2, 'Under Review'), (3, 'Approved'), (4, 'Awaiting Participant Signature'), (5, 'Signed by Participant'), (6, 'Signed by GP'), (7, 'Forfeited')], default='Draft'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Create'), (2, 'Delete'), (3, 'Forfeit'), (4, 'Dilute')]),
        ),
    ]
