# Generated by Django 3.2.16 on 2023-08-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0006_auto_20230816_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Draft'), (2, 'Under Review'), (3, 'Approved'), (4, 'Awaiting Participant Signature'), (5, 'Signed by Participant'), (6, 'Signed by GP'), (7, 'Forfeited')], default=1),
        ),
    ]
