# Generated by Django 3.2.16 on 2023-08-22 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0042_auto_20230706_2028'),
        ('carry_pools', '0007_alter_allocation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VestingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('vesting_type', models.PositiveSmallIntegerField(choices=[(1, 'Time Based'), (2, 'Event Based'), (3, 'Hybrid')])),
                ('is_default', models.BooleanField(default=False)),
                ('cliff_duration', models.DurationField(blank=True, null=True)),
                ('cliff_vesting_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=13, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vesting_schedules', to='companies.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeBasedVestingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('period_duration', models.DurationField()),
                ('period_vesting_percentage', models.DecimalField(decimal_places=4, max_digits=13)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('vesting_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_vesting_schedules', to='carry_pools.vestingschedule')),
            ],
            options={
                'ordering': ('vesting_schedule', 'sequence'),
            },
        ),
        migrations.CreateModel(
            name='MilestoneBasedVestingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('milestone_vesting_percentage', models.DecimalField(decimal_places=4, max_digits=13)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_schedules', to='carry_pools.milestone')),
                ('vesting_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_vesting_schedules', to='carry_pools.vestingschedule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
