# Generated by Django 3.2.16 on 2023-08-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0008_milestone_milestonebasedvestingschedule_timebasedvestingschedule_vestingschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestonebasedvestingschedule',
            name='is_accelerated',
            field=models.BooleanField(default=False),
        ),
    ]
