# Generated by Django 3.2.16 on 2023-08-24 10:56

from django.db import migrations
from django.utils import timezone
from dateutil.parser import parse


def create_vesting_schedules(apps, schema_editor):
    VestingSchedule = apps.get_model('carry_pools', 'VestingSchedule')
    TimeBasedVestingSchedule = apps.get_model('carry_pools', 'TimeBasedVestingSchedule')
    Milestone = apps.get_model('carry_pools', 'Milestone')
    MilestoneBasedVestingSchedule = apps.get_model('carry_pools', 'MilestoneBasedVestingSchedule')
    Company = apps.get_model('companies', 'Company')

    company = Company.objects.filter(slug='sidecar').first()
    if not company:
        return

    # Creating Time Based Schedule
    vesting_schedule_data = {
        'name': 'Time Based Vesting Schedule for Testing',
        'description': '4 year vesting, 1 year cliff - vests 25% after 12 months '
                       'then equal parts monthly i.e. 2.083% until 100% vested',
        'vesting_type': 1,
        'is_default': False,
        'cliff_duration': 'P1Y',
        'cliff_vesting_percentage': 25,
        'company': company
    }
    vesting_schedule = VestingSchedule.objects.create(**vesting_schedule_data)

    sequence = 1
    bulk_create_data = []
    for count in range(1, 36 + 1):
        if count == 36:
            period_vesting_percentage = 2.0845
        else:
            period_vesting_percentage = 2.0833

        data = {
            'vesting_schedule': vesting_schedule,
            'period_duration': 'P1M',
            'period_vesting_percentage': period_vesting_percentage,
            'sequence': sequence
        }
        sequence += 1
        bulk_create_data.append(data)

    TimeBasedVestingSchedule.objects.bulk_create([TimeBasedVestingSchedule(**data) for data in bulk_create_data])

    # Creating Milestone Based Schedule
    vesting_schedule_data = {
        'name': 'Milestone Based Vesting Schedule for Testing',
        'description': 'Vests 20% on deal date i.e. 2023-09-01, another 20% on first capital deployment i.e 2024-03-01,'
                       ' another 20% on second capital deployment i.e 2024-09-30,'
                       ' 100% vested upon liquidation i.e. on 2024-08-30',
        'vesting_type': 2,
        'is_default': False,
        'cliff_duration': None,
        'cliff_vesting_percentage': 0,
        'company': company
    }
    vesting_schedule = VestingSchedule.objects.create(**vesting_schedule_data)

    milestones_data = [
        {
            'name': 'Deal Date',
            'type': 'Deal Date',
            'date': '2023-09-01',
            'milestone_vesting_percentage': 20
        },
        {
            'name': 'First Capital Deployment',
            'type': 'Capital Deployment',
            'date': '2024-03-01',
            'milestone_vesting_percentage': 20
        },
        {
            'name': 'Second Capital Deployment',
            'type': 'Capital Deployment',
            'date': '2024-09-30',
            'milestone_vesting_percentage': 20
        },
        {
            'name': 'Liquidation',
            'type': 'Liquidation',
            'date': '2024-08-30',
            'is_accelerated': True,
            'milestone_vesting_percentage': 100
        }
    ]

    for milestone_data in milestones_data:
        date = parse(milestone_data.pop('date'))
        milestone_vesting_percentage = milestone_data.pop('milestone_vesting_percentage')
        is_accelerated = milestone_data.pop('is_accelerated') if 'is_accelerated' in milestone_data else False

        milestone = Milestone.objects.create(date=date, **milestone_data)
        MilestoneBasedVestingSchedule.objects.create(
            vesting_schedule=vesting_schedule,
            milestone=milestone,
            milestone_vesting_percentage=milestone_vesting_percentage,
            is_accelerated=is_accelerated
        )

    # Creating Hybrid Vesting Schedule
    vesting_schedule_data = {
        'name': 'Hybrid Vesting Schedule for Testing',
        'description': '80% vesting over 4 years, vests annual with a 1 year cliff, '
                       'then 100% vested on liquidation i.e on 2026-05-31',
        'vesting_type': 3,
        'is_default': False,
        'cliff_duration': 'P1Y',
        'cliff_vesting_percentage': 20,
        'company': company
    }
    vesting_schedule = VestingSchedule.objects.create(**vesting_schedule_data)

    sequence = 1
    bulk_create_data = []
    for count in range(1, 3 + 1):
        bulk_create_data.append({
            'vesting_schedule': vesting_schedule,
            'period_duration': 'P1Y',
            'period_vesting_percentage': 20,
            'sequence': sequence
        })
        sequence += 1

    TimeBasedVestingSchedule.objects.bulk_create([TimeBasedVestingSchedule(**data) for data in bulk_create_data])

    milestone = Milestone.objects.create(
        name='Liquidation',
        type='Liquidation',
        date=timezone.datetime(2026, 5, 31)
    )
    MilestoneBasedVestingSchedule.objects.create(
        vesting_schedule=vesting_schedule,
        milestone=milestone,
        milestone_vesting_percentage=100,
        is_accelerated=True
    )


def delete_vesting_schedules(apps, schema_editor):
    VestingSchedule = apps.get_model('carry_pools', 'VestingSchedule')

    names = [
        'Time Based Vesting Schedule for Testing',
        'Milestone Based Vesting Schedule for Testing',
        'Hybrid Vesting Schedule for Testing'
     ]
    vesting_schedules = VestingSchedule.objects.filter(name__in=names)
    vesting_schedules.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0009_milestonebasedvestingschedule_is_accelerated'),
    ]

    operations = [
        migrations.RunPython(create_vesting_schedules, delete_vesting_schedules),
    ]
