# Generated by Django 3.2.16 on 2023-08-29 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0010_auto_20230824_1056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Allocation',
            new_name='PoolAction',
        ),
        migrations.RenameField(
            model_name='fundcarrypool',
            old_name='bips',
            new_name='bps',
        ),
        migrations.RenameField(
            model_name='historicalfundcarrypool',
            old_name='bips',
            new_name='bps',
        ),
    ]
