# Generated by Django 3.2.16 on 2023-09-01 12:00

from django.db import migrations


def convert_bips_to_bps(apps, schema_editor):
    FundCarryPool = apps.get_model('carry_pools', 'FundCarryPool')

    def rename_field_key(data_list):
        for data in data_list:
            if 'bips' in data:
                data['bps'] = data.pop('bips')

            if 'pools' in data:
                rename_field_key(data['pools'])

            if 'participants' in data:
                rename_field_key(data['participants'])

    for fund_carry_pool in FundCarryPool.objects.all():
        rename_field_key(fund_carry_pool.participants)
        rename_field_key(fund_carry_pool.pools)
        fund_carry_pool.save()


def convert_bps_to_bips(apps, schema_editor):
    FundCarryPool = apps.get_model('carry_pools', 'FundCarryPool')

    def rename_field_key(data_list):
        for data in data_list:
            if 'bps' in data:
                data['bips'] = data.pop('bps')

            if 'pools' in data:
                rename_field_key(data['pools'])

            if 'participants' in data:
                rename_field_key(data['participants'])

    for fund_carry_pool in FundCarryPool.objects.all():
        rename_field_key(fund_carry_pool.participants)
        rename_field_key(fund_carry_pool.pools)
        fund_carry_pool.save()


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0011_auto_20230829_1140'),
    ]

    operations = [
        migrations.RunPython(convert_bips_to_bps, convert_bps_to_bips)
    ]
