# Generated by Django 3.2.16 on 2023-09-06 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carry_pools', '0012_auto_20230901_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Draft'), (2, 'Under Review'), (3, 'Approved'), (4, 'Awaiting Participant Signature'), (5, 'Signed by Participant'), (6, 'Signed by GP'), (7, 'Forfeited')], default=1)),
                ('grant_date', models.DateTimeField(blank=True, null=True)),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Create'), (2, 'Delete'), (3, 'Forfeit'), (4, 'Dilute')])),
                ('bps', models.DecimalField(blank=True, decimal_places=4, max_digits=13, null=True)),
                ('fund_external_id', models.CharField(max_length=120)),
                ('base_pool_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('parent_pool_id', models.CharField(blank=True, max_length=120, null=True)),
                ('pool_name', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('allocation_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_allocation_actions', to=settings.AUTH_USER_MODEL)),
                ('vesting_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_allocation_actions', to='carry_pools.vestingschedule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='PoolAction',
        ),
        migrations.RenameField(
            model_name='fundcarrypool',
            old_name='participants',
            new_name='allocations',
        ),
        migrations.RenameField(
            model_name='historicalfundcarrypool',
            old_name='participants',
            new_name='allocations',
        ),
    ]
