# Generated by Django 3.2.16 on 2023-09-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0013_auto_20230906_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationaction',
            name='bps',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
