# Generated by Django 3.2.16 on 2023-09-12 09:51

from django.db import migrations


def clear_data(apps, schema_editor):
    FundCarryPool = apps.get_model('carry_pools', 'FundCarryPool')
    AllocationAction = apps.get_model('carry_pools', 'AllocationAction')

    FundCarryPool.objects.all().delete()
    AllocationAction.objects.all().delete()


def reverse_clear_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0014_alter_allocationaction_bps'),
    ]

    operations = [
        migrations.RunPython(clear_data, reverse_clear_data),
    ]
