# Generated by Django 3.2.16 on 2023-09-12 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0064_historicalfund'),
        ('companies', '0042_auto_20230706_2028'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_users', '0006_auto_20230103_1142'),
        ('carry_pools', '0015_auto_20230912_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Draft'), (2, 'Under Review'), (3, 'Approved')], default=1)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carry_plans', to='companies.company')),
                ('default_vesting_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_associated_carry_plans', to='carry_pools.vestingschedule')),
                ('starting_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_carry_plans', to='carry_pools.carryplan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarryPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('bps', models.FloatField()),
                ('external_id', models.CharField(db_index=True, max_length=120)),
                ('pools', models.JSONField(default=list)),
                ('allocations', models.JSONField(default=list)),
                ('carry_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carry_pools', to='carry_pools.carryplan')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_carry_pools', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pools', to='admin_users.adminuser')),
                ('legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carry_pools.legalentity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FundCarryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('carry_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carry_plans', to='carry_pools.carryplan')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_carry_plans', to='funds.fund')),
            ],
            options={
                'unique_together': {('carry_plan', 'fund')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalCarryPool',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('modified_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('bps', models.FloatField()),
                ('external_id', models.CharField(db_index=True, max_length=120)),
                ('pools', models.JSONField(default=list)),
                ('allocations', models.JSONField(default=list)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('carry_plan', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carry_pools.carryplan')),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='admin_users.adminuser')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('legal_entity', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carry_pools.legalentity')),
            ],
            options={
                'verbose_name': 'historical carry pool',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name='historicalfundcarrypool',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalfundcarrypool',
            name='fund',
        ),
        migrations.RemoveField(
            model_name='historicalfundcarrypool',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalfundcarrypool',
            name='legal_entity',
        ),
        migrations.RemoveField(
            model_name='allocationaction',
            name='fund_external_id',
        ),
        migrations.AddField(
            model_name='allocationaction',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_allocations', to='companies.company'),
        ),
        migrations.DeleteModel(
            name='FundCarryPool',
        ),
        migrations.DeleteModel(
            name='HistoricalFundCarryPool',
        ),
    ]
