# Generated by Django 3.2.16 on 2023-09-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0016_auto_20230912_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='carryplan',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
