# Generated by Django 3.2.19 on 2023-10-24 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0067_merge_20231019_1808'),
        ('companies', '0045_merge_20231019_1808'),
        ('carry_pools', '0017_carryplan_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deal_name', models.CharField(max_length=120)),
                ('capital_deployed', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_deals', to='companies.company')),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fund_deals', to='funds.fund')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
