# Generated by Django 3.2.19 on 2023-10-26 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0018_deal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealCarryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('carry_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carry_plans_deals', to='carry_pools.carryplan')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_carry_plans', to='carry_pools.deal')),
            ],
            options={
                'unique_together': {('carry_plan', 'deal')},
            },
        ),
    ]
