# Generated by Django 3.2.16 on 2023-10-27 09:44

from api.libs.utils.nanoid_generator import generate_nanoid
from django.db import migrations, models


def set_default_external_id(apps, schema_editor):
    Deal = apps.get_model('carry_pools', 'Deal')
    for deal in Deal.objects.all():
        deal.external_id = generate_nanoid()
        deal.save()


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0019_dealcarryplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='deal_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='deal',
            name='external_id',
            field=models.CharField(db_index=True, default=generate_nanoid, max_length=120),
        ),
        migrations.RunPython(set_default_external_id),
    ]