# Generated by Django 3.2.19 on 2023-12-11 09:41

from django.db import migrations
from django.utils import timezone
from dateutil.parser import parse


def create_vesting_schedules(apps, schema_editor):
    VestingSchedule = apps.get_model('carry_pools', 'VestingSchedule')
    TimeBasedVestingSchedule = apps.get_model('carry_pools', 'TimeBasedVestingSchedule')
    Milestone = apps.get_model('carry_pools', 'Milestone')
    MilestoneBasedVestingSchedule = apps.get_model('carry_pools', 'MilestoneBasedVestingSchedule')
    Company = apps.get_model('companies', 'Company')

    company = Company.objects.filter(slug='sidecar').first()
    if not company:
        return

    # Creating Time Based Schedule 1
    vesting_schedule_data = {
        'name': 'Time Based Vesting Schedule 1',
        'description': '10% vesting annually over 10 years straight',
        'vesting_type': 1,
        'is_default': False,
        'cliff_duration': None,
        'cliff_vesting_percentage': 0,
        'company': company
    }
    vesting_schedule = VestingSchedule.objects.create(**vesting_schedule_data)

    sequence = 1
    bulk_create_data = []
    for count in range(1, 10 + 1):
        period_vesting_percentage = 10.0000
        data = {
            'vesting_schedule': vesting_schedule,
            'period_duration': 'P1Y',
            'period_vesting_percentage': period_vesting_percentage,
            'sequence': sequence
        }
        sequence += 1
        bulk_create_data.append(data)

    TimeBasedVestingSchedule.objects.bulk_create([TimeBasedVestingSchedule(**data) for data in bulk_create_data])

    # Creating Time Based Schedule 2
    vesting_schedule_data = {
        'name': 'Time Based Vesting Schedule 2',
        'description': '80% vesting annually over the first 5 years, 20% annually over the last 5 years',
        'vesting_type': 1,
        'is_default': False,
        'cliff_duration': None,
        'cliff_vesting_percentage': 0,
        'company': company
    }
    vesting_schedule = VestingSchedule.objects.create(**vesting_schedule_data)

    sequence = 1
    bulk_create_data = []
    for count in range(1, 10 + 1):
        if sequence > 5:
            period_vesting_percentage = 4.0000
        else:
            period_vesting_percentage = 16.0000
        data = {
            'vesting_schedule': vesting_schedule,
            'period_duration': 'P1Y',
            'period_vesting_percentage': period_vesting_percentage,
            'sequence': sequence
        }
        sequence += 1
        bulk_create_data.append(data)

    TimeBasedVestingSchedule.objects.bulk_create([TimeBasedVestingSchedule(**data) for data in bulk_create_data])

    # Creating Time Based Schedule 3
    vesting_schedule_data = {
        'name': 'Time Based Vesting Schedule 3',
        'description': '7 year with annual vesting',
        'vesting_type': 1,
        'is_default': False,
        'cliff_duration': None,
        'cliff_vesting_percentage': 0,
        'company': company
    }
    vesting_schedule = VestingSchedule.objects.create(**vesting_schedule_data)

    sequence = 1
    bulk_create_data = []
    for count in range(1, 7 + 1):
        if sequence == 7:
            period_vesting_percentage = 14.2858
        else:
            period_vesting_percentage = 14.2857
        data = {
            'vesting_schedule': vesting_schedule,
            'period_duration': 'P1Y',
            'period_vesting_percentage': period_vesting_percentage,
            'sequence': sequence
        }
        sequence += 1
        bulk_create_data.append(data)

    TimeBasedVestingSchedule.objects.bulk_create([TimeBasedVestingSchedule(**data) for data in bulk_create_data])

    # Creating Time Based Schedule 4
    vesting_schedule_data = {
        'name': 'Time Based Vesting Schedule 4',
        'description': '5 year straight',
        'vesting_type': 1,
        'is_default': False,
        'cliff_duration': None,
        'cliff_vesting_percentage': 0,
        'company': company
    }
    vesting_schedule = VestingSchedule.objects.create(**vesting_schedule_data)

    sequence = 1
    bulk_create_data = []
    for count in range(1, 5 + 1):
        period_vesting_percentage = 20.0000
        data = {
            'vesting_schedule': vesting_schedule,
            'period_duration': 'P1Y',
            'period_vesting_percentage': period_vesting_percentage,
            'sequence': sequence
        }
        sequence += 1
        bulk_create_data.append(data)

    TimeBasedVestingSchedule.objects.bulk_create([TimeBasedVestingSchedule(**data) for data in bulk_create_data])

    # Creating Time Based Schedule 5
    vesting_schedule_data = {
        'name': 'Time Based Vesting Schedule 5',
        'description': '5 year straight, 1 year cliff with 20% vesting after the end of the first year, monthly vesting afterwards',
        'vesting_type': 1,
        'is_default': False,
        'cliff_duration': 'P1Y',
        'cliff_vesting_percentage': 20,
        'company': company
    }
    vesting_schedule = VestingSchedule.objects.create(**vesting_schedule_data)

    sequence = 1
    bulk_create_data = []
    for count in range(1, 48 + 1):
        if sequence == 48:
            period_vesting_percentage = 1.6698
        else:
            period_vesting_percentage = 1.6666
        data = {
            'vesting_schedule': vesting_schedule,
            'period_duration': 'P1M',
            'period_vesting_percentage': period_vesting_percentage,
            'sequence': sequence
        }
        sequence += 1
        bulk_create_data.append(data)

    TimeBasedVestingSchedule.objects.bulk_create([TimeBasedVestingSchedule(**data) for data in bulk_create_data])

    # Creating Milestone Based Schedule
    vesting_schedule_data = {
        'name': 'Milestone Based Vesting Schedule Option 1',
        'description': 'Vests 10% on fund close date, another 10% on first investment made,'
                       'another 20% on first distribution received,'
                       'another 25% on final investment made,'
                       ' 100% vested upon liquidation',
        'vesting_type': 2,
        'is_default': False,
        'cliff_duration': None,
        'cliff_vesting_percentage': 0,
        'company': company
    }
    vesting_schedule = VestingSchedule.objects.create(**vesting_schedule_data)

    milestones_data = [
        {
            'name': 'Fund Close',
            'type': 'Fund Close',
            'date': '2024-12-31',
            'milestone_vesting_percentage': 10
        },
        {
            'name': 'First Investment Made',
            'type': 'First Investment Made',
            'date': '2025-12-31',
            'milestone_vesting_percentage': 10
        },
        {
            'name': 'First Distribution Received',
            'type': 'First Distribution Received',
            'date': '2027-12-31',
            'milestone_vesting_percentage': 20
        },
        {
            'name': 'Final Investment Made',
            'type': 'Final Investment Made',
            'date': '2029-12-31',
            'milestone_vesting_percentage': 25
        },
        {
            'name': 'Liquidation',
            'type': 'Liquidation',
            'date': '2033-12-31',
            'is_accelerated': True,
            'milestone_vesting_percentage': 100
        }
    ]

    for milestone_data in milestones_data:
        date = parse(milestone_data.pop('date'))
        milestone_vesting_percentage = milestone_data.pop('milestone_vesting_percentage')
        is_accelerated = milestone_data.pop('is_accelerated') if 'is_accelerated' in milestone_data else False

        milestone = Milestone.objects.create(date=date, **milestone_data)
        MilestoneBasedVestingSchedule.objects.create(
            vesting_schedule=vesting_schedule,
            milestone=milestone,
            milestone_vesting_percentage=milestone_vesting_percentage,
            is_accelerated=is_accelerated
        )

    # Creating Hybrid Vesting Schedule 1
    vesting_schedule_data = {
        'name': 'Hybrid Vesting Schedule Option 1',
        'description': '20% vests at the end of the first year,'
                       '10% vesting annually per year for 6 years,'
                       '20% one-time at liquidation',
        'vesting_type': 3,
        'is_default': False,
        'cliff_duration': None,
        'cliff_vesting_percentage': 0,
        'company': company
    }
    vesting_schedule = VestingSchedule.objects.create(**vesting_schedule_data)

    sequence = 1
    bulk_create_data = []
    for count in range(1, 7 + 1):
        if sequence == 1:
            bulk_create_data.append({
                'vesting_schedule': vesting_schedule,
                'period_duration': 'P1Y',
                'period_vesting_percentage': 20,
                'sequence': sequence
            })
        else:
            bulk_create_data.append({
                'vesting_schedule': vesting_schedule,
                'period_duration': 'P1Y',
                'period_vesting_percentage': 10,
                'sequence': sequence
            })
        sequence += 1

    TimeBasedVestingSchedule.objects.bulk_create([TimeBasedVestingSchedule(**data) for data in bulk_create_data])

    milestone = Milestone.objects.create(
        name='Liquidation',
        type='Liquidation',
        date=timezone.datetime(2033, 12, 31)
    )
    MilestoneBasedVestingSchedule.objects.create(
        vesting_schedule=vesting_schedule,
        milestone=milestone,
        milestone_vesting_percentage=100,
        is_accelerated=True
    )

    # Creating Hybrid Vesting Schedule 2
    vesting_schedule_data = {
        'name': 'Hybrid Vesting Schedule Option 2',
        'description': '10% cliff end of the first year, 4 milestones throughout the fund,'
                       '1 time based in the middle at 5 years,'
                       'and liquidation milestone',
        'vesting_type': 3,
        'is_default': False,
        'cliff_duration': 'P1Y',
        'cliff_vesting_percentage': 10,
        'company': company
    }
    vesting_schedule = VestingSchedule.objects.create(**vesting_schedule_data)

    sequence = 1
    bulk_create_data = [{
        'vesting_schedule': vesting_schedule,
        'period_duration': 'P5Y',
        'period_vesting_percentage': 15,
        'sequence': sequence
    }]
    TimeBasedVestingSchedule.objects.bulk_create([TimeBasedVestingSchedule(**data) for data in bulk_create_data])

    milestones_data = [
        {
            'name': 'First Investment made',
            'type': 'First Investment made',
            'date': '2025-12-31',
            'milestone_vesting_percentage': 10
        },
        {
            'name': 'First Distribution Made',
            'type': 'First Distribution Made',
            'date': '2027-12-31',
            'milestone_vesting_percentage': 15
        },
        {
            'name': '100% of Capital Deployed',
            'type': '100% of Capital Deployed',
            'date': '2028-12-31',
            'milestone_vesting_percentage': 15
        },
        {
            'name': 'Fund is breakeven with hurdle rate',
            'type': 'Fund is breakeven with hurdle rate',
            'date': '2031-12-31',
            'milestone_vesting_percentage': 15
        },
        {
            'name': 'Liquidation',
            'type': 'Liquidation',
            'date': '2033-12-31',
            'is_accelerated': True,
            'milestone_vesting_percentage': 100
        }
    ]

    for milestone_data in milestones_data:
        date = parse(milestone_data.pop('date'))
        milestone_vesting_percentage = milestone_data.pop('milestone_vesting_percentage')
        is_accelerated = milestone_data.pop('is_accelerated') if 'is_accelerated' in milestone_data else False

        milestone = Milestone.objects.create(date=date, **milestone_data)
        MilestoneBasedVestingSchedule.objects.create(
            vesting_schedule=vesting_schedule,
            milestone=milestone,
            milestone_vesting_percentage=milestone_vesting_percentage,
            is_accelerated=is_accelerated
        )


def delete_vesting_schedules(apps, schema_editor):
    VestingSchedule = apps.get_model('carry_pools', 'VestingSchedule')
    names = [
        'Time Based Vesting Schedule 1',
        'Time Based Vesting Schedule 2',
        'Time Based Vesting Schedule 3',
        'Time Based Vesting Schedule 4',
        'Time Based Vesting Schedule 5',
        'Milestone Based Vesting Schedule Option 1',
        'Hybrid Vesting Schedule Option 1',
        'Hybrid Vesting Schedule Option 2'
     ]
    vesting_schedules = VestingSchedule.objects.filter(name__in=names)
    vesting_schedules.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0020_auto_20231027_0944'),
    ]

    operations = [
        migrations.RunPython(create_vesting_schedules, delete_vesting_schedules),
    ]
