# Generated by Django 3.2.19 on 2023-12-06 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0020_auto_20231027_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
    ]
