# Generated by Django 3.2.22 on 2023-12-07 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0021_auto_20231207_0349'),
        ('companies', '0046_alter_company_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employment_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprofile',
            name='employment_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_profile', to='employment_records.employmentrecord'),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AddField(
            model_name='historicalparticipantprofile',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='companies.company'),
        ),
        migrations.AddField(
            model_name='historicalparticipantprofile',
            name='employment_record',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employment_records.employmentrecord'),
        ),
        migrations.AddField(
            model_name='historicalparticipantprofile',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalparticipantprofile',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
