# Generated by Django 3.2.22 on 2023-12-11 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0021_auto_20231211_0941'),
        ('carry_pools', '0022_auto_20231207_0349'),
    ]

    operations = [
    ]
