# Generated by Django 3.2.19 on 2023-12-12 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0021_auto_20231206_0927'),
        ('carry_pools', '0023_merge_0021_auto_20231211_0941_0022_auto_20231207_0349'),
    ]

    operations = [
    ]
