# Generated by Django 3.2.19 on 2023-12-15 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0024_merge_20231212_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealcarryplan',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_carry_plan', to='carry_pools.deal'),
        ),
    ]
