# Generated by Django 3.2.19 on 2024-01-09 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0006_auto_20230103_1142'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0066_auto_20230720_1236'),
        ('companies', '0046_alter_company_logo'),
        ('workflows', '0033_alter_workflow_managers'),
        ('carry_pools', '0025_alter_dealcarryplan_deal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('show_everytime', models.BooleanField(blank=True, default=None, null=True)),
                ('require_signature', models.BooleanField(default=False)),
                ('require_wet_signature', models.BooleanField(default=False)),
                ('require_gp_signature', models.BooleanField(default=False)),
                ('document_type', models.PositiveSmallIntegerField(choices=[(1, 'Carry Award'), (2, 'Carry Forfeiture')], default=1)),
                ('requirements', models.PositiveSmallIntegerField(choices=[(1, 'Signature'), (2, 'Acknowledgement')], default=2)),
                ('document_status', models.BooleanField(default=True)),
                ('carry_plans', models.ManyToManyField(related_name='associated_carry_documents', to='carry_pools.CarryPlan')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_carry_documents', to='companies.company')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_associated_carry_documents', to='documents.document')),
                ('gp_signer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carry_document_gp_signer', to='admin_users.adminuser')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ParticipantCarryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('gp_signing_complete', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('envelope_id', models.CharField(blank=True, max_length=80, null=True)),
                ('carry_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carry_document_users', to='carry_pools.carrydocument')),
                ('carry_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carry_plan_participant_document', to='carry_pools.carryplan')),
                ('certificate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_carry_document_certificates', to='documents.document')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants_carry_documents', to='companies.company')),
                ('signed_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_participant_carry_documents', to='documents.document')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_participant_carry_document', to='workflows.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_carry_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
