# Generated by Django 3.2.23 on 2024-01-17 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carry_pools', '0026_carrydocument_participantcarrydocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_participant_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
