# Generated by Django 3.2.19 on 2024-03-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0027_alter_participantprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantcarrydocument',
            name='allocation_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
