# Generated by Django 3.2.19 on 2024-04-15 10:07

from django.db import migrations, models


def set_default_date(apps, schema_editor):
    CarryPlan = apps.get_model('carry_pools', 'CarryPlan')
    CarryPlan.objects.all().update(vesting_start_date=models.F('created_at'))


class Migration(migrations.Migration):
    dependencies = [
        ('carry_pools', '0028_participantcarrydocument_allocation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='carryplan',
            name='vesting_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(set_default_date),
    ]
