# Generated by Django 3.2.19 on 2024-05-16 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('companies', '0046_alter_company_logo'),
        ('carry_pools', '0029_carryplan_vesting_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='date',
        ),
        migrations.AddField(
            model_name='milestone',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='company_milestones', to='companies.company'),
        ),
        migrations.CreateModel(
            name='CarryPlanMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('carry_plan',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carry_plan_milestones',
                                   to='carry_pools.carryplan')),
                ('milestone',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_carry_plans',
                                   to='carry_pools.milestone')),
            ],
            options={
                'unique_together': {('carry_plan', 'milestone')},
            },
        ),
    ]
