# Generated by Django 3.2.19 on 2024-05-16 12:54

from django.db import migrations
from django.db.transaction import atomic


def re_configure_milestones(apps, schema_editor):
    with atomic():
        Company = apps.get_model('companies', 'Company')
        Milestone = apps.get_model('carry_pools', 'Milestone')
        MilestoneBasedVestingSchedule = apps.get_model('carry_pools', 'MilestoneBasedVestingSchedule')
        VestingSchedule = apps.get_model('carry_pools', 'VestingSchedule')

        default_milestones = [
            "Deal Date",
            "First Capital Deployment",
            "Second Capital Deployment",
            "Liquidation",
            "Fund Close",
            "First Investment Made",
            "First Distribution Received",
            "First Distribution Made",
            "Fund is BreakEven With Hurdle Rate",
            "100% of Capital Deployed",
            "Final Investment Made"
        ]
        companies = Company.objects.all()
        for company in companies:
            for milestone in default_milestones:
                Milestone.objects.create(
                    name=milestone,
                    type=milestone,
                    company=company
                )

        vesting_schedules = VestingSchedule.objects.all()
        for vesting_schedule in vesting_schedules:
            company = vesting_schedule.company

            milestone_based_schedules = MilestoneBasedVestingSchedule.objects.filter(
                vesting_schedule=vesting_schedule
            )
            for milestone_schedule in milestone_based_schedules:
                previous_milestone_id = milestone_schedule.milestone.id
                previous_milestone_name = Milestone.objects.get(pk=previous_milestone_id).name.lower()

                new_milestone = Milestone.objects.filter(
                    company=company,
                    name__iexact=previous_milestone_name
                ).first()

                milestone_schedule.milestone = new_milestone
                milestone_schedule.save()

        Milestone.objects.filter(company=None).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('carry_pools', '0030_auto_20240516_1054'),
    ]

    operations = [
        migrations.RunPython(re_configure_milestones),
    ]
