# Generated by Django 3.2.19 on 2024-05-17 10:31

from django.db import migrations


def assign_allocation_id_to_allocations(apps, schema_editor):
    CarryPool = apps.get_model('carry_pools', 'CarryPool')
    for pool in CarryPool.objects.all():
        carry_plan_id = pool.carry_plan.id
        allocations = pool.allocations
        for allocation in allocations:
            allocation['carry_plan_id'] = carry_plan_id
        # Update the allocations field directly without calling save()
        CarryPool.objects.filter(pk=pool.pk).update(allocations=allocations)


class Migration(migrations.Migration):
    dependencies = [
        ('carry_pools', '0031_auto_20240516_1254'),
    ]

    operations = [
        migrations.RunPython(assign_allocation_id_to_allocations),
    ]
