# Generated by Django 3.2.19 on 2024-05-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0032_auto_20240517_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carryplanmilestone',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
