# Generated by Django 3.2.25 on 2024-05-23 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employment_records', '0002_auto_20240520_1745'),
        ('carry_pools', '0033_alter_carryplanmilestone_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantprofile',
            name='employment_record',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='employment_records.employmentrecord'),
        ),
        migrations.AlterModelTable(
            name='participantprofile',
            table='participant_profiles',
        ),
        migrations.RemoveField(
            model_name='participantprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='participantprofile',
            name='employment_record',
        ),
        migrations.RemoveField(
            model_name='participantprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalParticipantProfile',
        ),
        migrations.DeleteModel(
            name='ParticipantProfile',
        ),
    ]
