# Generated by Django 3.2.19 on 2024-06-27 11:23

from django.db import migrations
from django.db.transaction import atomic


def initialize_vesting_start_in_allocations(apps, schema_editor):
    with atomic():
        CarryPool = apps.get_model('carry_pools', 'CarryPool')
        for pool in CarryPool.objects.all():
            carry_plan_vesting_start_date = pool.carry_plan.vesting_start_date.strftime("%Y-%m-%d")
            allocations = pool.allocations
            for allocation in allocations:
                allocation['vesting_start_date'] = carry_plan_vesting_start_date
            # Update the allocations field directly without calling save(), to avoid additional record creation
            CarryPool.objects.filter(pk=pool.pk).update(allocations=allocations)


class Migration(migrations.Migration):
    dependencies = [
        ('carry_pools', '0034_alter_participantprofile_employment_record'),
    ]

    operations = [
        migrations.RunPython(initialize_vesting_start_in_allocations),
    ]
