# Generated by Django 3.2.19 on 2024-07-03 10:23

from django.db import migrations
from django.db.transaction import atomic


def initialize_no_vesting_schedule(apps, schema_editor):
    with atomic():
        Company = apps.get_model('companies', 'Company')
        VestingSchedule = apps.get_model('carry_pools', 'VestingSchedule')
        for company in Company.objects.all():
            vesting_schedule_data = {
                'name': 'No Vesting',
                'description': 'No Vesting',
                'vesting_type': 1,
                'is_default': False,
                'cliff_duration': 'P0M',
                'cliff_vesting_percentage': 100,
                'company': company
            }
            VestingSchedule.objects.create(**vesting_schedule_data)


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0035_auto_20240627_1123'),
    ]

    operations = [
        migrations.RunPython(initialize_no_vesting_schedule),
    ]
