# Generated by Django 3.2.19 on 2024-07-12 11:48

from django.db import migrations
from django.db.transaction import atomic


def initialize_carry_participants_allocations(apps, schema_editor):
    with atomic():
        Company = apps.get_model('companies', 'Company')
        CarryPool = apps.get_model('carry_pools', 'CarryPool')
        RetailUser = apps.get_model('users', 'RetailUser')
        CarryParticipant = apps.get_model('carry_pools', 'CarryParticipant')
        CarryParticipantUser = apps.get_model('carry_pools', 'CarryParticipantUser')
        AllocationAction = apps.get_model('carry_pools', 'AllocationAction')

        for company in Company.objects.all():
            user_to_participant_map = {}

            # get all existing user ids in all carry pools for this company
            existing_user_ids = set()
            for carry_pool in CarryPool.objects.filter(company=company):
                allocations = carry_pool.allocations
                for allocation in allocations:
                    existing_user_ids.add(allocation.get('user_id'))

            # create carry participant record for each user, and create map
            for user_id in existing_user_ids:
                user = RetailUser.objects.get(pk=user_id)
                carry_participant = CarryParticipant.objects.create(
                    first_name=user.first_name if user.first_name else " ",
                    last_name=user.last_name if user.last_name else " ",
                    company=company
                )
                CarryParticipantUser.objects.create(
                    user=user,
                    carry_participant=carry_participant
                )
                user_to_participant_map[user_id] = carry_participant.id

            # map user id to carry participant id in all allocations
            for carry_pool in CarryPool.objects.filter(company=company):
                allocations = carry_pool.allocations
                for allocation in allocations:
                    allocation['carry_participant_id'] = user_to_participant_map[allocation['user_id']]
                    allocation.pop('user_id')
                # Update the allocations field directly without calling save(), to avoid additional record creation
                CarryPool.objects.filter(pk=carry_pool.pk).update(allocations=allocations)

            # map allocation actions
            for allocation_action in AllocationAction.objects.filter(company=company):
                allocation_action.carry_participant_id = user_to_participant_map[allocation_action.user.id]
                allocation_action.save()


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0037_auto_20240712_1147'),
    ]

    operations = [
        migrations.RunPython(initialize_carry_participants_allocations),
    ]
