# Generated by Django 3.2.19 on 2024-07-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0038_auto_20240712_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocationaction',
            name='user',
        ),
    ]
