# Generated by Django 3.2.19 on 2024-07-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0039_remove_allocationaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='carryparticipant',
            name='entity_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
