# Generated by Django 3.2.19 on 2024-07-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0040_carryparticipant_entity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carryparticipant',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
