# Generated by Django 3.2.23 on 2024-08-08 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0046_alter_company_logo'),
        ('carry_pools', '0041_alter_carryparticipant_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarryShareClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('legal_name', models.CharField(max_length=120)),
                ('common_name', models.CharField(max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_carry_share_classes', to='companies.company')),
                ('vesting_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carry_pools.vestingschedule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarryVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('legal_name', models.CharField(max_length=120)),
                ('common_name', models.CharField(max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_vehicles', to='companies.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarryVehicleShareClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('template_share_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carry_pools.carryshareclass')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carry_pools.carryvehicle')),
                ('vesting_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carry_pools.vestingschedule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
