# Generated by Django 3.2.25 on 2024-08-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0041_alter_carryparticipant_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationaction',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carryparticipant',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carryparticipantuser',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deal',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='milestone',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='milestonebasedvestingschedule',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timebasedvestingschedule',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vestingschedule',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
