# Generated by Django 3.2.23 on 2024-08-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0042_carryshareclass_carryvehicle_carryvehicleshareclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='carryshareclass',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carryshareclass',
            name='common_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
