# Generated by Django 3.2.25 on 2024-08-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0042_auto_20240819_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='carryplanmilestone',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dealcarryplan',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fundcarryplan',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
