# Generated by Django 3.2.19 on 2024-08-19 13:18

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0042_auto_20240812_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparticipantdistribution',
            name='escrow_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalparticipantdistribution',
            name='net_distribution',
            field=api.models.EncryptedDecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historicalparticipantdistribution',
            name='points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participantdistribution',
            name='escrow_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participantdistribution',
            name='net_distribution',
            field=api.models.EncryptedDecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='participantdistribution',
            name='points',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
