# Generated by Django 3.2.25 on 2024-08-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0043_auto_20240809_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='carryvehicleshareclass',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
