# Generated by Django 3.2.19 on 2024-08-20 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0043_auto_20240819_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantdistribution',
            name='distribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_participants', to='carry_pools.distribution'),
        ),
    ]
