# Generated by Django 3.2.19 on 2024-08-22 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0044_alter_participantdistribution_distribution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalparticipantdistribution',
            old_name='allocation',
            new_name='allocation_id',
        ),
        migrations.RenameField(
            model_name='participantdistribution',
            old_name='allocation',
            new_name='allocation_id',
        ),
    ]
