# Generated by Django 3.2.25 on 2024-08-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0044_carryvehicleshareclass_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='carryshareclass',
            name='require_no_share_class',
            field=models.BooleanField(default=False),
        ),
    ]
