# Generated by Django 3.2.25 on 2024-08-13 09:55

from django.db import migrations
from django.db.transaction import atomic


def add_no_share_class_requirement(apps, schema_editor):
    with atomic():
        Company = apps.get_model('companies', 'Company')
        CarryShareClass = apps.get_model('carry_pools', 'CarryShareClass')

        for company in Company.objects.all():
            CarryShareClass.objects.get_or_create(
                company=company,
                require_no_share_class=True,
                defaults={
                    'legal_name': 'No Share Class/Single Share Class',
                    'description': 'No Share Class/Single Share Class',
                }
            )


class Migration(migrations.Migration):
    dependencies = [
        ('carry_pools', '0045_carryshareclass_require_no_share_class'),
    ]

    operations = [
        migrations.RunPython(add_no_share_class_requirement, reverse_code=migrations.RunPython.noop)
    ]
