# Generated by Django 3.2.25 on 2024-08-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0046_auto_20240813_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='fair_market_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
    ]
