# Generated by Django 3.2.25 on 2024-08-22 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0045_auto_20240822_1243'),
        ('carry_pools', '0046_auto_20240813_0955'),
    ]

    operations = [
    ]
