# Generated by Django 3.2.19 on 2024-08-23 11:35

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0047_merge_0045_auto_20240822_1243_0046_auto_20240813_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='amount',
            field=api.models.EncryptedDecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='escrow',
            field=api.models.EncryptedDecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='historicaldistribution',
            name='amount',
            field=api.models.EncryptedDecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='historicaldistribution',
            name='escrow',
            field=api.models.EncryptedDecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='historicalparticipantdistribution',
            name='amount',
            field=api.models.EncryptedDecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='historicalparticipantdistribution',
            name='escrow',
            field=api.models.EncryptedDecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='historicalparticipantdistribution',
            name='net_distribution',
            field=api.models.EncryptedDecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrealization',
            name='amount',
            field=api.models.EncryptedDecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='participantdistribution',
            name='amount',
            field=api.models.EncryptedDecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='participantdistribution',
            name='escrow',
            field=api.models.EncryptedDecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='participantdistribution',
            name='net_distribution',
            field=api.models.EncryptedDecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='realization',
            name='amount',
            field=api.models.EncryptedDecimalField(decimal_places=2, max_digits=13),
        ),
    ]
