# Generated by Django 3.2.19 on 2024-08-23 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0047_deal_fair_market_value'),
        ('carry_pools', '0047_merge_0045_auto_20240822_1243_0046_auto_20240813_0955'),
    ]

    operations = [
    ]
