# Generated by Django 3.2.25 on 2024-08-23 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0048_auto_20240823_1135'),
        ('carry_pools', '0048_merge_20240823_1421'),
    ]

    operations = [
    ]
