# Generated by Django 3.2.19 on 2024-08-26 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0049_merge_20240823_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrySubPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('bps', models.FloatField()),
                ('deleted', models.BooleanField(default=False)),
                ('carry_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carry_plan_subpools', to='carry_pools.carryplan')),
                ('template_share_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carry_pools.carryshareclass')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carry_pools.carryvehicle')),
                ('vesting_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carry_pools.vestingschedule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
