# Generated by Django 3.2.19 on 2024-08-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0050_carrysubpool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carryplan',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Unpublished Change'), (2, 'Under Review'), (3, 'Published')], default=1),
        ),
    ]
