# Generated by Django 3.2.19 on 2024-09-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0051_alter_carryplan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='carryplanmilestone',
            name='vesting_percentage',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=13, null=True),
        ),
    ]
