# Generated by Django 3.2.25 on 2024-09-02 19:07

from django.db import migrations, models
import django.db.models.deletion


def migrate(apps, schema_editor):
    DealRealization = apps.get_model('carry_pools', 'DealRealization')
    for realization in DealRealization.objects.all():
        realization.deal = realization.deal_carry_plan.deal
        realization.save()


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0052_carryplanmilestone_vesting_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealrealization',
            name='deal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='realizations',
                                    to='carry_pools.deal'),
        ),
        migrations.AddField(
            model_name='historicaldealrealization',
            name='deal',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='carry_pools.deal'),
        ),
        migrations.RunPython(migrate),
        migrations.RemoveField(
            model_name='dealrealization',
            name='deal_carry_plan',
        ),
        migrations.RemoveField(
            model_name='historicaldealrealization',
            name='deal_carry_plan',
        ),
    ]
