# Generated by Django 3.2.25 on 2024-09-02 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0053_auto_20240902_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealrealization',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realizations', to='carry_pools.deal'),
        ),
    ]
