# Generated by Django 3.2.25 on 2024-09-09 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0043_auto_20240819_1706'),
        ('carry_pools', '0054_alter_dealrealization_deal'),
    ]

    operations = [
    ]
