# Generated by Django 3.2.25 on 2024-09-12 09:26

from django.db import migrations
from django.db.transaction import atomic

from api.carry_pools.constants import CARRY_PLAN_PUBLISH_FEATURE_FLAG


def add_default_feature_flag(apps, schema_editor):
    with atomic():
        Company = apps.get_model('companies', 'Company')
        Feature = apps.get_model("feature_flags", "Feature")
        CompanyFeatureFlag = apps.get_model("feature_flags", "CompanyFeatureFlag")
        feature_flag_name = CARRY_PLAN_PUBLISH_FEATURE_FLAG

        for company in Company.objects.all():
            feature_instance, created = Feature.objects.get_or_create(name=feature_flag_name)
            CompanyFeatureFlag.objects.update_or_create(
                feature=feature_instance,
                company_id=company.id,
                defaults={'active': False}
            )

class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0055_merge_20240909_1723'),
        ('feature_flags', '0004_auto_20240523_0819'),
    ]

    operations = [
        migrations.RunPython(add_default_feature_flag, reverse_code=migrations.RunPython.noop)
    ]
