# Generated by Django 3.2.25 on 2024-09-27 09:13

import api.carry_pools.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0056_auto_20240912_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='timebasedvestingschedule',
            name='period_vesting_percentage_denominator',
            field=models.IntegerField(blank=True, null=True, validators=[api.carry_pools.models.non_zero_validator]),
        ),
        migrations.AddField(
            model_name='timebasedvestingschedule',
            name='period_vesting_percentage_numerator',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
