# Generated by Django 3.2.25 on 2024-09-30 12:47

import api.carry_pools.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0057_auto_20240927_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='vestingschedule',
            name='cliff_vesting_percentage_denominator',
            field=models.IntegerField(blank=True, null=True, validators=[api.carry_pools.models.non_zero_validator]),
        ),
        migrations.AddField(
            model_name='vestingschedule',
            name='cliff_vesting_percentage_numerator',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
