# Generated by Django 3.2.25 on 2024-10-01 11:36
from collections import namedtuple

from django.db import migrations
from django.db.transaction import atomic
from fractions import  Fraction

def vesting_add_fractions(apps, schema_editor):
    with atomic():
        Company = apps.get_model('companies', 'Company')
        VestingSchedule = apps.get_model('carry_pools', 'VestingSchedule')

        CustomDataTuple = namedtuple(
            'CustomDataTuple', [
                'period_numerator',
                'period_denominator',
                'cliff_numerator',
                'cliff_denominator']
        )

        custom_schedule_data = {
            'timebasedvestingschedule3': CustomDataTuple(
                period_numerator=100,
                period_denominator=7,
                cliff_numerator=None,
                cliff_denominator=None
            ),
            'timebasedvestingschedule5': CustomDataTuple(
                period_numerator=5,
                period_denominator=3,
                cliff_numerator=20,
                cliff_denominator=1
            ),
            'timebasedvestingschedule': CustomDataTuple(
                period_numerator=25,
                period_denominator=12,
                cliff_numerator=25,
                cliff_denominator=1
            ),
            'timebasedvestingschedulefortesting': CustomDataTuple(
                period_numerator=25,
                period_denominator=12,
                cliff_numerator=25,
                cliff_denominator=1
            ),
            '7years,5monthcliff': CustomDataTuple(
                period_numerator=25,
                period_denominator=21,
                cliff_numerator=125,
                cliff_denominator=21
            ),
            '6years,2yearcliff': CustomDataTuple(
                period_numerator=25,
                period_denominator=18,
                cliff_numerator=100,
                cliff_denominator=3
            ),
            '10years,nocliff': CustomDataTuple(
                period_numerator=5,
                period_denominator=6,
                cliff_numerator=None,
                cliff_denominator=None
            ),
            '5years,nocliff': CustomDataTuple(
                period_numerator=5,
                period_denominator=3,
                cliff_numerator=None,
                cliff_denominator=None
            ),
            '3years,nocliff': CustomDataTuple(
                period_numerator=25,
                period_denominator=9,
                cliff_numerator=None,
                cliff_denominator=None
            ),
            '10years,3yearcliff': CustomDataTuple(
                period_numerator=5,
                period_denominator=6,
                cliff_numerator=30,
                cliff_denominator=1
            ),
            '3years,1yearcliff': CustomDataTuple(
                period_numerator=25,
                period_denominator=9,
                cliff_numerator=100,
                cliff_denominator=3
            ),
            'novesting': CustomDataTuple(
                period_numerator=None,
                period_denominator=None,
                cliff_numerator=100,
                cliff_denominator=1
            ),

        }

        for company in Company.objects.all():
            vesting_schedules = VestingSchedule.objects.filter(company=company)
            for vesting_schedule in vesting_schedules:
                if vesting_schedule.vesting_type == 2:
                    continue
                name = vesting_schedule.name.replace(" ", "").lower()
                if name not in custom_schedule_data:
                    if vesting_schedule.cliff_duration:
                        cliff_percentage = vesting_schedule.cliff_vesting_percentage
                        cliff_percentage_fraction = Fraction(cliff_percentage).limit_denominator()
                        vesting_schedule.cliff_vesting_percentage_numerator = cliff_percentage_fraction.numerator
                        vesting_schedule.cliff_vesting_percentage_denominator = cliff_percentage_fraction.denominator
                        vesting_schedule.save()

                    time_schedules = vesting_schedule.time_vesting_schedules.all()
                    for schedule in time_schedules:
                        vesting_percentage = schedule.period_vesting_percentage
                        percentage_fraction = Fraction(vesting_percentage).limit_denominator()
                        schedule.period_vesting_percentage_numerator = percentage_fraction.numerator
                        schedule.period_vesting_percentage_denominator = percentage_fraction.denominator
                        schedule.save()

                else:
                    data : CustomDataTuple = custom_schedule_data[name]
                    if data.cliff_numerator and data.cliff_denominator:
                        vesting_schedule.cliff_vesting_percentage_numerator = data.cliff_numerator
                        vesting_schedule.cliff_vesting_percentage_denominator = data.cliff_denominator
                        vesting_schedule.save()

                    time_schedules = vesting_schedule.time_vesting_schedules.all()
                    for schedule in time_schedules:
                        schedule.period_vesting_percentage_numerator = data.period_numerator
                        schedule.period_vesting_percentage_denominator = data.period_denominator
                        schedule.save()



class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0058_auto_20240930_1247'),
    ]

    operations = [
        migrations.RunPython(vesting_add_fractions, reverse_code=migrations.RunPython.noop)
    ]
