# Generated by Django 3.2.25 on 2024-10-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0059_auto_20241001_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carryplan',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Unpublished Change'), (2, 'Pending Approval'), (3, 'Published'), (4, 'Approved'), (5, 'Unapproved')], default=1),
        ),
    ]
