# Generated by Django 3.2.25 on 2024-10-15 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0034_alter_workflow_module'),
        ('carry_pools', '0060_alter_carryplan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='carryplan',
            name='workflow',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_carry_plan', to='workflows.workflow'),
        ),
    ]
