# Generated by Django 3.2.25 on 2024-10-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0061_carryplan_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carryplan',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Unpublished Changes'), (2, 'Pending Approval'), (3, 'Published'), (4, 'Approved-unpublished'), (5, 'Unapproved')], default=1),
        ),
    ]
