# Generated by Django 3.2.25 on 2024-10-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0062_alter_carryplan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrypool',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Unpublished Changes'), (2, 'Pending Approval'), (3, 'Published'), (4, 'Approved-unpublished'), (5, 'Unapproved')], default=1),
        ),
        migrations.AddField(
            model_name='historicalcarrypool',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Unpublished Changes'), (2, 'Pending Approval'), (3, 'Published'), (4, 'Approved-unpublished'), (5, 'Unapproved')], default=1),
        ),
    ]
