# Generated by Django 3.2.25 on 2024-10-20 22:11

from django.db import migrations
from django.db.transaction import atomic


def approve_all_carry_pools(apps, schema_editor):
    with atomic():
        CarryPool = apps.get_model('carry_pools', 'CarryPool')
        for pool in CarryPool.objects.all():
            # Update the allocations field directly without calling save(), to avoid additional record creation
            CarryPool.objects.filter(pk=pool.pk).update(status=4)


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0063_auto_20241020_2210'),
    ]

    operations = [
        migrations.RunPython(approve_all_carry_pools),
    ]
