# Generated by Django 3.2.25 on 2024-10-23 12:37

from django.db import migrations
from django.db.transaction import atomic


def release_all_documents(apps, schema_editor):
    with atomic():
        ParticipantCarryDocument = apps.get_model('carry_pools', 'ParticipantCarryDocument')
        ParticipantCarryDocument.objects.all().update(is_released=True)


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0065_participantcarrydocument_is_released'),
    ]

    operations = [
        migrations.RunPython(release_all_documents, reverse_code=migrations.RunPython.noop),
    ]
