# Generated by Django 3.2.25 on 2024-11-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0066_auto_20241023_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='vestingschedule',
            name='custom_display',
            field=models.JSONField(null=True),
        ),
    ]
