# Generated by Django 3.2.25 on 2024-11-04 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0066_auto_20241023_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carryplan',
            name='default_vesting_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_associated_carry_plans', to='carry_pools.vestingschedule'),
        ),
        migrations.AlterField(
            model_name='carryplan',
            name='starting_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_carry_plans', to='carry_pools.carryplan'),
        ),
    ]
