# Generated by Django 3.2.25 on 2024-10-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0066_auto_20241023_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldistribution',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
