# Generated by Django 3.2.25 on 2024-11-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0066_auto_20241023_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundrealization',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalfundrealization',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
