# Generated by Django 3.2.25 on 2024-10-28 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0046_alter_company_logo'),
        ('carry_pools', '0067_auto_20241028_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarryDistributionAPILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('request_path', models.TextField()),
                ('request_body', models.JSONField()),
                ('request_method', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carry_distributions_api_logs', to='companies.company')),
            ],
            options={
                'db_table': 'carry_distributions_api_logs',
            },
        ),
    ]
