# Generated by Django 3.2.25 on 2024-11-04 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0067_auto_20241031_1237'),
        ('carry_pools', '0068_carrydistributionapilog'),
    ]

    operations = [
    ]
