# Generated by Django 3.2.25 on 2024-11-06 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0067_auto_20241104_1203'),
        ('carry_pools', '0069_merge_20241104_1731'),
    ]

    operations = [
    ]
