# Generated by Django 3.2.25 on 2024-11-12 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0067_vestingschedule_custom_display'),
        ('carry_pools', '0070_merge_20241106_1835'),
    ]

    operations = [
    ]
