# Generated by Django 3.2.25 on 2024-11-26 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0067_auto_20241101_1236'),
        ('carry_pools', '0071_merge_20241112_1814'),
    ]

    operations = [
    ]
