# Generated by Django 3.2.25 on 2024-11-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0071_merge_20241112_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='estimated_value_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='fair_market_value_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
