# Generated by Django 3.2.25 on 2024-12-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0072_merge_20241126_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationaction',
            name='bps',
            field=models.DecimalField(blank=True, decimal_places=24, max_digits=28, null=True),
        ),
    ]
