# Generated by Django 3.2.25 on 2024-12-11 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0072_auto_20241125_1244'),
        ('carry_pools', '0073_alter_allocationaction_bps'),
    ]

    operations = [
    ]
