# Generated by Django 3.2.25 on 2024-12-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0073_alter_allocationaction_bps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carryplan',
            old_name='vesting_start_date',
            new_name='effective_date',
        ),
    ]
