# Generated by Django 3.2.25 on 2024-12-11 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0074_auto_20241209_1248'),
        ('carry_pools', '0074_merge_20241211_1413'),
    ]

    operations = [
    ]
