# Generated by Django 3.2.25 on 2024-12-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0075_merge_20241211_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrysubpool',
            name='bps',
            field=models.DecimalField(blank=True, decimal_places=24, max_digits=28, null=True),
        ),
    ]
