# Generated by Django 3.2.25 on 2025-01-23 11:56

import api.libs.utils.nanoid_generator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0076_alter_carrysubpool_bps'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentTranche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=120)),
                ('external_id', models.CharField(db_index=True, default=api.libs.utils.nanoid_generator.generate_nanoid, max_length=120)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('fair_market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('estimated_value_date', models.DateField(blank=True, null=True)),
                ('fair_market_value_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_investment_tranche', to='companies.company')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_investment_tranches', to='carry_pools.deal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvestmentTrancheCarryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('carry_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carry_plan_investment_tranche', to='carry_pools.carryplan')),
                ('investment_tranche', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investment_tranche_carry_plan', to='carry_pools.investmenttranche')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
