# Generated by Django 3.2.25 on 2025-02-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0078_historicalinvestmenttranche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationaction',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Create'), (2, 'Delete'), (3, 'Forfeit'), (4, 'Dilute'), (5, 'Edit')]),
        ),
    ]
