# Generated by Django 3.2.25 on 2025-03-07 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0048_company_show_new_commitment_flow'),
        ('carry_pools', '0079_alter_allocationaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarryGpCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('source_external_id', models.CharField(max_length=120)),
                ('source_type', models.PositiveSmallIntegerField(choices=[(1, 'Fund'), (2, 'Deal'), (3, 'Investment Tranche')])),
                ('total_capital_commit', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('cashless_commit', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('management_fee_offset', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('salary_reduction', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('carry_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_gp_commits', to='carry_pools.carryparticipant')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_carry_gp_commits', to='companies.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
