# Generated by Django 3.2.25 on 2025-03-07 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0080_carrygpcommitment'),
        ('carry_pools', '0080_historicalinvestmenttrancherealization_investmenttrancherealization'),
    ]

    operations = [
    ]
