# Generated by Django 3.2.25 on 2025-03-10 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0080_auto_20250307_1122'),
        ('carry_pools', '0081_merge_20250307_1642'),
    ]

    operations = [
    ]
