# Generated by Django 3.2.25 on 2025-03-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0082_merge_20250310_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvestmenttrancherealization',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investmenttrancherealization',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
