# Generated by Django 3.2.25 on 2025-03-18 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0083_auto_20250310_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrydocument',
            name='sub_pools',
            field=models.ManyToManyField(related_name='subpool_carry_documents', to='carry_pools.CarrySubPool'),
        ),
        migrations.AddField(
            model_name='participantcarrydocument',
            name='sub_pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_pool_participant_document', to='carry_pools.carrysubpool'),
        ),
    ]
