# Generated by Django 3.2.25 on 2025-03-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0083_auto_20250310_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrygpcommitment',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
