# Generated by Django 3.2.25 on 2025-03-20 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0084_auto_20250318_1300'),
        ('carry_pools', '0084_carrygpcommitment_deleted'),
    ]

    operations = [
    ]
