# Generated by Django 3.2.25 on 2025-04-16 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0085_merge_20250320_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarryHurdle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('hurdle_rate', models.DecimalField(decimal_places=2, max_digits=13)),
                ('is_supercharged', models.BooleanField(default=False)),
                ('source_allocation_id', models.CharField(max_length=120)),
                ('impacted_allocations_ids', models.JSONField(blank=True, default=list)),
                ('carry_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carry_plan_hurdles', to='carry_pools.carryplan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
