# Generated by Django 3.2.25 on 2025-04-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0085_merge_20250320_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationaction',
            name='transferred_from_allocation_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='allocationaction',
            name='transferred_to_allocation_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='allocationaction',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Create'), (2, 'Delete'), (3, 'Forfeit'), (4, 'Dilute'), (5, 'Edit'), (6, 'Transfer From'), (7, 'Transfer To')]),
        ),
    ]
