# Generated by Django 3.2.25 on 2025-04-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0086_carryhurdle'),
    ]

    operations = [
        migrations.AddField(
            model_name='carryhurdle',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
