# Generated by Django 3.2.25 on 2025-04-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0087_carryhurdle_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='carryhurdle',
            name='impact_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Even'), (2, 'Pro Rata')], default=1),
        ),
    ]
