# Generated by Django 3.2.25 on 2025-04-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0088_carryhurdle_impact_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='carryhurdle',
            name='supercharge_end_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
    ]
