# Generated by Django 3.2.25 on 2025-05-06 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0008_auto_20250225_1133'),
        ('carry_pools', '0089_carryhurdle_supercharge_end_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationValueAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('allocation_id', models.CharField(max_length=120)),
                ('deleted', models.BooleanField(default=False)),
                ('value_type', models.PositiveSmallIntegerField(choices=[(1, 'Estimated Value'), (2, 'Fair Market Value')])),
                ('effective_date', models.DateField()),
                ('adjustment', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('carry_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carry_plan_value_adjustments', to='carry_pools.carryplan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_value_adjustments', to='admin_users.adminuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
