# Generated by Django 3.2.25 on 2025-05-05 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0086_auto_20250410_1322'),
        ('carry_pools', '0089_carryhurdle_supercharge_end_value'),
    ]

    operations = [
    ]
