# Generated by Django 3.2.25 on 2025-05-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0090_allocationvalueadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationvalueadjustment',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
