# Generated by Django 3.2.25 on 2025-05-08 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0090_merge_20250505_1454'),
        ('carry_pools', '0091_allocationvalueadjustment_note'),
    ]

    operations = [
    ]
