# Generated by Django 3.2.25 on 2025-05-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0092_merge_20250508_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='carryhurdle',
            name='trigger_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Estimated Carry Value'), (2, 'Fair Market Value'), (3, 'Both ECV and FMV')], default=1),
        ),
    ]
