# Generated by Django 3.2.25 on 2025-05-13 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0093_carryhurdle_trigger_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carryhurdle',
            old_name='trigger_type',
            new_name='applies_to',
        ),
    ]
