# Generated by Django 3.2.25 on 2025-07-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carry_pools', '0094_rename_trigger_type_carryhurdle_applies_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='vestingschedule',
            name='vesting_duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
