# Generated by Django 3.2.13 on 2023-02-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0011_auto_20220630_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationcomment',
            name='document_field_label',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalapplicationcomment',
            name='document_field_label',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
