# Generated by Django 3.2.13 on 2023-02-28 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0012_applicationcommentreply_historicalapplicationcommentreply'),
        ('comments', '0012_auto_20230227_1900'),
    ]

    operations = [
    ]
