# Generated by Django 3.2.13 on 2023-03-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0013_merge_20230228_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationcomment',
            name='document_field_label',
        ),
        migrations.RemoveField(
            model_name='historicalapplicationcomment',
            name='document_field_label',
        ),
        migrations.AddField(
            model_name='applicationcomment',
            name='comment_label',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalapplicationcomment',
            name='comment_label',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
