# Generated by Django 3.2.13 on 2023-03-31 14:06

from django.db import migrations
from api.cards.default import CARDS_FIELD_LABEL_MAPPING


def update_comments_labels(apps, schema_editor):
    Comment = apps.get_model('comments', 'ApplicationComment')
    Document = apps.get_model('documents', 'Document')
    for comment in Comment.objects.all():
        if comment.document_identifier:
            try:
                document = Document.objects.get(document_id=comment.document_identifier)
                comment.comment_label = document.title
                comment.save()
            except Document.DoesNotExist:
                pass
        elif comment.question_identifier in CARDS_FIELD_LABEL_MAPPING:
            comment.comment_label = CARDS_FIELD_LABEL_MAPPING[comment.question_identifier]
            comment.save()


class Migration(migrations.Migration):
    dependencies = [
        ('comments', '0014_auto_20230302_1305'),
    ]

    operations = [
        migrations.RunPython(update_comments_labels),
    ]
