PARTICIPANT_COMPENSATION_VIEW_CONFIG = {
    "cash_tiles": [
        {
            "id": 1,
            "heading": "Salary",
            "field_name": "cash.salary",
            "enabled": True,
            "is_sortable": True,
            "field_type": "currency",
        },
        {
            "id": 2,
            "heading": "Bonus",
            "field_name": "cash.total_bonus",
            "enabled": True,
            "is_sortable": True,
            "field_type": "currency",
        },
    ],
    "benefits_breakdown": [
        {
            "id": 1,
            "heading": "401k",
            "field_name": "cash.match_401k",
            "enabled": True,
            "is_sortable": True,
            "field_type": "currency",
        },
        {
            "id": 2,
            "heading": "Medical",
            "field_name": "insurance_benefits.medical",
            "enabled": True,
            "field_type": "currency",
            "is_sortable": True,
        },
        {
            "id": 3,
            "heading": "Dental",
            "field_name": "insurance_benefits.dental",
            "enabled": True,
            "field_type": "currency",
            "is_sortable": True,
        },

        {
            "id": 4,
            "heading": "Vision",
            "field_name": "insurance_benefits.vision",
            "enabled": True,
            "field_type": "currency",
            "is_sortable": True,
        },
        {
            "id": 5,
            "heading": "Life",
            "field_name": "insurance_benefits.life",
            "field_type": "currency",
            "enabled": True,
            "is_sortable": True,
        },
        {
            "id": 6,
            "heading": "LTD",
            "field_name": "insurance_benefits.ltd",
            "enabled": True,
            "is_sortable": True,
            "field_type": "currency",
        },
        {
            "id": 7,
            "heading": "Supplemental LTD",
            "field_name": "insurance_benefits.supplemental_ltd",
            "enabled": True,
            "is_sortable": True,
            "field_type": "currency",
        },
        {
            "id": 8,
            "heading": "AD&D",
            "field_name": "insurance_benefits.ad_and_d",
            "enabled": True,
            "is_sortable": True,
            "field_type": "currency",
        },
        {
            "id": 9,
            "heading": "Phone",
            "field_name": "misc_benefits.phone",
            "enabled": True,
            "is_sortable": True,
            "field_type": "currency",
        },
        {
            "id": 10,
            "heading": "Meals",
            "field_name": "misc_benefits.meals",
            "enabled": True,
            "is_sortable": True,
            "field_type": "currency",
        },
        {
            "id": 11,
            "heading": "Parking/Metro",
            "field_name": "misc_benefits.parking",
            "enabled": True,
            "is_sortable": True,
            "field_type": "currency",
        }
    ],
    "tables": [
        {
            "heading": "Compensation History",
            "rows": [
                {
                    "id": 0,
                    "heading": "Year",
                    "field_name": "year",
                    "enabled": True,
                    "field_type": "int",
                    "is_sortable": False,
                },
                {
                    "id": 1,
                    "heading": "Salary",
                    "field_name": "cash.salary",
                    "enabled": True,
                    "is_sortable": True,
                    "field_type": "currency",
                },
                {
                    "id": 2,
                    "heading": "Bonus",
                    "field_name": "cash.total_bonus",
                    "enabled": True,
                    "is_sortable": True,
                    "field_type": "currency",
                },
                {
                    "id": 3,
                    "heading": "401k",
                    "field_name": "cash.match_401k",
                    "enabled": True,
                    "is_sortable": True,
                    "field_type": "currency",
                },
                {
                    "id": 4,
                    "heading": "Medical",
                    "field_name": "insurance_benefits.medical",
                    "enabled": True,
                    "field_type": "currency",
                    "is_sortable": True,
                },
                {
                    "id": 5,
                    "heading": "Dental",
                    "field_name": "insurance_benefits.dental",
                    "enabled": True,
                    "field_type": "currency",
                    "is_sortable": True,
                },

                {
                    "id": 6,
                    "heading": "Vision",
                    "field_name": "insurance_benefits.vision",
                    "enabled": True,
                    "field_type": "currency",
                    "is_sortable": True,
                },
                {
                    "id": 7,
                    "heading": "Life",
                    "field_name": "insurance_benefits.life",
                    "field_type": "currency",
                    "enabled": True,
                    "is_sortable": True,
                },
                {
                    "id": 8,
                    "heading": "LTD",
                    "field_name": "insurance_benefits.ltd",
                    "enabled": True,
                    "is_sortable": True,
                    "field_type": "currency",
                },
                {
                    "id": 9,
                    "heading": "Supplemental LTD",
                    "field_name": "insurance_benefits.supplemental_ltd",
                    "enabled": True,
                    "is_sortable": True,
                    "field_type": "currency",
                },
                {
                    "id": 10,
                    "heading": "AD&D",
                    "field_name": "insurance_benefits.ad_and_d",
                    "enabled": True,
                    "is_sortable": True,
                    "field_type": "currency",
                },
                {
                    "id": 11,
                    "heading": "Phone",
                    "field_name": "misc_benefits.phone",
                    "enabled": True,
                    "is_sortable": True,
                    "field_type": "currency",
                },
                {
                    "id": 12,
                    "heading": "Meals",
                    "field_name": "misc_benefits.meals",
                    "enabled": True,
                    "is_sortable": True,
                    "field_type": "currency",
                },
                {
                    "id": 13,
                    "heading": "Parking",
                    "field_name": "misc_benefits.parking",
                    "enabled": True,
                    "is_sortable": True,
                    "field_type": "currency",
                },

            ]
        }
    ]
}
