# Generated by Django 3.2.16 on 2023-06-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_usernotification_fund_capital_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
