# Generated by Django 3.2.16 on 2023-06-20 10:10

from django.db import migrations
from api.notifications.models import UserNotification


def delete_user_notifications(apps, schema_editor):
    user_notification = apps.get_model('notifications', 'UserNotification')
    user_notification.objects.filter(
        notification_type=UserNotification.NotificationTypeChoice.NEW_INVESTMENT.value
    ).update(deleted=True)


def undelete_user_notifications(apps, schema_editor):
    user_notification = apps.get_model('notifications', 'UserNotification')
    user_notification.objects.filter(
        notification_type=UserNotification.NotificationTypeChoice.NEW_INVESTMENT.value
    ).update(deleted=False)


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_usernotification_deleted'),
    ]

    operations = [
        migrations.RunPython(delete_user_notifications, undelete_user_notifications),
    ]
