# Generated by Django 3.2.18 on 2023-08-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_auto_20230620_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='is_admin_upload',
            field=models.BooleanField(default=False),
        ),
    ]
