# Generated by Django 3.2.25 on 2025-02-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_auto_20230928_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
