# Generated by Django 3.2.25 on 2025-06-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_usernotification_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdocument',
            name='production_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='notificationdocument',
            name='staging_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='production_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='staging_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
