# Generated by Django 3.2.23 on 2024-03-18 09:28

from django.db import migrations


def create_aggregator_flag(apps, schema_editor):
    Feature = apps.get_model("feature_flags", "Feature")
    coinvest_feature, _ = Feature.objects.get_or_create(
        name="Aggregator",
        defaults={"description": "enables access to Aggregator dashboards"}
    )


def delete_aggregator_flag(apps, schema_editor):
    Feature = apps.get_model("feature_flags", "Feature")
    Feature.objects.filter(name="Aggregator").delete()


class Migration(migrations.Migration):
    dependencies = [
        ('feature_flags', '0002_coinvest_activation'),
    ]

    operations = [
        migrations.RunPython(create_aggregator_flag, reverse_code=delete_aggregator_flag)
    ]
