# Generated by Django 3.2.23 on 2024-05-23 08:19

from django.db import migrations


def create_excel_export_flag(apps, schema_editor):
    Feature = apps.get_model("feature_flags", "Feature")
    coinvest_feature, _ = Feature.objects.get_or_create(
        name="excel_export_flag",
        defaults={"description": "enables excel export feature"}
    )


class Migration(migrations.Migration):
    dependencies = [
        ('feature_flags', '0003_auto_20240318_0928'),
    ]

    operations = [
        migrations.RunPython(create_excel_export_flag, migrations.RunPython.noop)
    ]
