# Generated by Django 3.2.25 on 2024-07-23 12:47

from django.db import migrations


def create_participant_list_view_top_nav_bar_feature(apps, schema_editor):
    Feature = apps.get_model("feature_flags", "Feature")
    CompanyFeatureFlag = apps.get_model("feature_flags", "CompanyFeatureFlag")
    Company = apps.get_model("companies", "Company")
    feature, _ = Feature.objects.get_or_create(
        name="participants_index_view",
        defaults={"description": "toggles on top nav bar participant index view"}
    )
    for c in Company.objects.all():
        CompanyFeatureFlag.objects.get_or_create(
            feature=feature,
            company=c,
            defaults={"active": False}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('feature_flags', '0004_auto_20240523_0819'),
    ]

    operations = [
        migrations.RunPython(create_participant_list_view_top_nav_bar_feature, migrations.RunPython.noop)
    ]
