# Generated by Django 3.2.25 on 2024-07-23 12:47

from django.db import migrations


def create_participant_list_view_top_nav_bar_feature(apps, schema_editor):
    Feature = apps.get_model("feature_flags", "Feature")
    CompanyFeatureFlag = apps.get_model("feature_flags", "CompanyFeatureFlag")
    Company = apps.get_model("companies", "Company")
    for feature in Feature.objects.all():
        for c in Company.objects.all():
            CompanyFeatureFlag.objects.get_or_create(
                feature=feature,
                company=c,
                defaults={"active": False}
            )


class Migration(migrations.Migration):

    dependencies = [
        ('feature_flags', '0005_auto_20240723_1247'),
    ]

    operations = [
        migrations.RunPython(create_participant_list_view_top_nav_bar_feature, migrations.RunPython.noop)
    ]
