# Generated by Django 3.2.25 on 2024-07-23 12:47

from django.db import migrations


def create_participant_list_view_top_nav_bar_feature(apps, schema_editor):
    Feature = apps.get_model("feature_flags", "Feature")
    CompanyFeatureFlag = apps.get_model("feature_flags", "CompanyFeatureFlag")
    Company = apps.get_model("companies", "Company")
    feature, _ = Feature.objects.get_or_create(
        name="carry_management_admin_commitments_tab",
        defaults={"description": "toggles display of Commitments tab in Carry Management for admin app"},
    )
    for c in Company.objects.all():
        CompanyFeatureFlag.objects.get_or_create(
            feature=feature,
            company=c,
            defaults={"active": False}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('feature_flags', '0007_auto_20250213_1616'),
    ]

    operations = [
        migrations.RunPython(create_participant_list_view_top_nav_bar_feature, migrations.RunPython.noop)
    ]
