# Generated by Django 3.2.25 on 2024-07-23 12:47

from django.db import migrations


def create_carry_hurdle_feature_flag(apps, schema_editor):
    Feature = apps.get_model("feature_flags", "Feature")
    CompanyFeatureFlag = apps.get_model("feature_flags", "CompanyFeatureFlag")
    Company = apps.get_model("companies", "Company")
    feature, _ = Feature.objects.get_or_create(
        name="carry_hurdle",
        defaults={"description": "toggles carry hurdle CRUD"},
    )
    for c in Company.objects.all():
        CompanyFeatureFlag.objects.get_or_create(
            feature=feature,
            company=c,
            defaults={"active": False}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('feature_flags', '0008_auto_20250327_1339'),
    ]

    operations = [
        migrations.RunPython(create_carry_hurdle_feature_flag, migrations.RunPython.noop)
    ]
