# Generated by Django 3.2.25 on 2025-05-06 15:21

from django.db import migrations


def create_transfers_feature_flag(apps, schema_editor):
    Feature = apps.get_model("feature_flags", "Feature")
    CompanyFeatureFlag = apps.get_model("feature_flags", "CompanyFeatureFlag")
    Company = apps.get_model("companies", "Company")
    feature, _ = Feature.objects.get_or_create(
        name="carry_points_transfer",
        defaults={"description": "toggles carry transfers"},
    )
    for c in Company.objects.all():
        CompanyFeatureFlag.objects.get_or_create(
            feature=feature,
            company=c,
            defaults={"active": False}
        )

class Migration(migrations.Migration):

    dependencies = [
        ('feature_flags', '0009_auto_20250425_0943'),
    ]

    operations = [
        migrations.RunPython(create_transfers_feature_flag, migrations.RunPython.noop)
    ]
