# Generated by Django 3.2.25 on 2025-05-08 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_flags', '0010_auto_20250506_1521'),
        ('feature_flags', '0010_auto_20250507_0945'),
    ]

    operations = [
    ]
