# Generated by Django 3.2.25 on 2025-05-14 09:42

from django.db import migrations


def create_portfolio_page_flag(apps, schema_editor):
    Feature = apps.get_model("feature_flags", "Feature")
    CompanyFeatureFlag = apps.get_model("feature_flags", "CompanyFeatureFlag")
    Company = apps.get_model("companies", "Company")
    feature, _ = Feature.objects.get_or_create(
        name="investor_portfolio_page",
        defaults={"description": "Page to show investor portfolio page"},
    )
    for c in Company.objects.all():
        CompanyFeatureFlag.objects.get_or_create(
            feature=feature,
            company=c,
            defaults={"active": False}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('feature_flags', '0011_merge_0010_auto_20250506_1521_0010_auto_20250507_0945'),
    ]

    operations = [
        migrations.RunPython(create_portfolio_page_flag, migrations.RunPython.noop)
    ]
