# Generated by Django 3.2.25 on 2025-05-19 12:46

from django.db import migrations

def create_multiple_currency_portfolio_page_flag(apps, schema_editor):
    Feature = apps.get_model("feature_flags", "Feature")
    CompanyFeatureFlag = apps.get_model("feature_flags", "CompanyFeatureFlag")
    Company = apps.get_model("companies", "Company")
    feature, _ = Feature.objects.get_or_create(
        name="multiple_currencies_in_portfolio",
        defaults={"description": "Flag to show multiple currencies in investor portfolio page"},
    )
    for c in Company.objects.all():
        CompanyFeatureFlag.objects.get_or_create(
            feature=feature,
            company=c,
            defaults={"active": False}
        )



class Migration(migrations.Migration):

    dependencies = [
        ('feature_flags', '0012_auto_20250514_0942'),
    ]

    operations = [
        migrations.RunPython(create_multiple_currency_portfolio_page_flag, migrations.RunPython.noop)
    ]
