CARDS_FIELD_LABEL_MAPPING = {
    "applicant_owned_by_another_entity": "Is the applicant a wholly-owned or majority-owned subsidiary of another entity?",
    "direct_parent_owned_by_another_entity": "Is the direct parent of the applicant a wholly-owned or majority-owned subsidiary of another entity?",
    "applicant_organized_for_specific_purpose_of_investing": "Was the applicant organised for the specific purpose of investing in the Fund?",
    "entity_title": "What is your title for signing on behalf of your entity?",
    "date_of_birth": "Date of birth",
    "email": "Email",
    "phone_number": "Phone Number",
    "is_lasalle_or_jll_employee": "A current employee",
    "is_us_citizen": "U.S. Person or investing for the direct or indirect benefit of a U.S. Person",
    "net_worth": "Net Worth",
    "citizenship_country": "Country of citizenship",
    "uk_national_insurance_number": "UK National Insurance Number",
    "pollitically_exposed_person": "Are you a politically exposed person, close associate of a politically exposed person, or a family member of a politically exposed person?",
    "source_of_funds": "Source of funds",
    "source_of_funds_other": "Fill in the source of funds",
    "source_of_funds_sale": "Fill in the details for sales proceeds",
    "source_of_funds_profession": "Profession",
    "economic_beneficiary": "Economic Beneficiary",
    "purpose_of_the_subscription": "Purpose of the subscription",
    "purpose_of_the_subscription_other": "Fill in the purpose of the subscription",
    "home_address": "Address",
    "home_city": "City",
    "home_zip": "Postal Code",
    "proof_of_identity_section": "Proof of Identity",
    "id_issuing_country": "Issuing Country",
    "id_expiration_date": "ID Expiration",
    "number_of_id": "Identification Number for the ID",
    "id_doc_image": "ID Document Image",
    "proof_of_address": "Proof of Address",
    "general_partnership_is_a_private_company": "Is the General Partner a Private Company?",
    "date_of_formation": "Date of Formation",
    "jurisdiction": "Jurisdiction",
    "jurisdiction_state": "State",
    "first_name": "First Name",
    "last_name": "Last Name",
    "occupation": "Occupation",
    "source_of_wealth": "Source of Wealth",
    "one_director": "One Director",
    "office_location": "Office Location",
    "id_document_type": "ID Document Type",
    "home_country": "Country",
    "home_state": "State",
    "home_region": "Region",
    "office_location": "Office Location",
    "citizenship_country": "Citizenship of Country",
    "is_us_citizen": "U.S. Person or investing for the direct or indirect benefit of a U.S. Person",
    "proof_of_identity-proof-of-identity-note": "Proof of identity",
    "evidence_of_beneficial_ownership": "Provide evidence of beneficial ownership structure of the Limited Partnership",
    "certified_copy_of_partnership_agreement": "Certified copy of Partnership Agreement, Deed or other document",
    "certificate_of_formation": "Certificate of Formation or jurisdictional equivalent",
    "list_of_directors_or_managers_of_partner": "List of current directors / managers of the General Partner",
    "list_of_authorized_signatories": "List of authorized signatories",
    "list_of_shareholders_members_owners": "List of shareholders / members / owners",
    "applicable_resolutions_power_of_attorney_auth_letter": "Any applicable resolutions, powers of attorney or authorisation letters authorizing the investor’s investment (if applicable)",
    "certified_copy_of_partnership_agreement_for_general_partnership": "Upload a certified copy of your partnership agreement",
    "trust_deeds_or_agreements": "Trust deed or agreement (or equivalent constitutional document)",
    "trust_applicable_resolutions_powers_of_attorney_or_authorization letters": "Any applicable resolutions, powers of attorney or authorisation letters authorizing the investor’s investment",

}
