# Generated by Django 3.2.23 on 2024-03-29 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firms', '0001_initial'),
        ('companies', '0046_alter_company_logo'),
        ('funds', '0073_auto_20240318_0949'),
        ('investors', '0031_alter_fundinvestor_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionalConsideration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('notice_date', models.DateField(db_index=True)),
                ('quarter', models.PositiveSmallIntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')])),
                ('capital_called', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('distributed', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('other_activity', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('net_transaction', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_transactional_considerations', to='companies.company')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firm_transactional_considerations', to='firms.firm')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_transactional_considerations', to='funds.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_transactional_considerations', to='investors.investor')),
            ],
        ),
        migrations.CreateModel(
            name='TaxConsideration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('notice_date', models.DateField(db_index=True)),
                ('quarter', models.PositiveSmallIntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')])),
                ('non_taxable', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('ltcg', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('stcg', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('ordinary', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('dividend', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('character_unknown', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_tax_considerations', to='companies.company')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firm_tax_considerations', to='firms.firm')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_tax_considerations', to='funds.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_tax_considerations', to='investors.investor')),
            ],
        ),
        migrations.AddConstraint(
            model_name='transactionalconsideration',
            constraint=models.UniqueConstraint(fields=('fund_id', 'firm_id', 'investor_id', 'notice_date'), name='unique_transactional_considerations'),
        ),
        migrations.AddConstraint(
            model_name='taxconsideration',
            constraint=models.UniqueConstraint(fields=('fund_id', 'firm_id', 'investor_id', 'notice_date'), name='unique_tax_considerations'),
        ),
    ]
