# Generated by Django 3.2.23 on 2024-03-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionalconsideration',
            name='character_unknown',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='transactionalconsideration',
            name='dividend',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='transactionalconsideration',
            name='ltcg',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='transactionalconsideration',
            name='non_taxable',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='transactionalconsideration',
            name='ordinary',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='transactionalconsideration',
            name='stcg',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
    ]
