# Generated by Django 3.2.23 on 2024-04-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_auto_20240331_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionalconsideration',
            name='conversion_rate',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=18),
        ),
        migrations.DeleteModel(
            name='TaxConsideration',
        ),
    ]
