# Generated by Django 3.2.23 on 2024-04-04 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_auto_20240404_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionalconsideration',
            name='conversion_rate',
        ),
    ]
