# Generated by Django 3.2.23 on 2024-04-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0004_remove_transactionalconsideration_conversion_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionalconsideration',
            name='conversion_rate',
            field=models.FloatField(default=1),
        ),
    ]
