# Generated by Django 3.2.19 on 2024-04-04 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0046_alter_company_logo'),
        ('investors', '0031_alter_fundinvestor_unique_together'),
        ('firms', '0001_initial'),
        ('funds', '0073_auto_20240318_0949'),
        ('notices', '0005_transactionalconsideration_conversion_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationConsideration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('quarter', models.PositiveSmallIntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')])),
                ('reported_fair_market_value', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('leverage_fund_line', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('net_asset_value', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('adjusted_values', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('net_asset_value_usd', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('reported_unfunded', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('commitment', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('unfunded_commitment_usd', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('conversion_rate', models.FloatField(default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_valuation_considerations', to='companies.company')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firm_valuation_considerations', to='firms.firm')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_valuation_considerations', to='funds.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_valuation_considerations', to='investors.investor')),
            ],
        ),
        migrations.AddConstraint(
            model_name='valuationconsideration',
            constraint=models.UniqueConstraint(fields=('fund_id', 'firm_id', 'investor_id'), name='unique_valuation_considerations'),
        ),
    ]
