# Generated by Django 3.2.23 on 2024-04-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0005_transactionalconsideration_conversion_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionalconsideration',
            name='total_taxable',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
    ]
