# Generated by Django 3.2.23 on 2024-04-05 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0006_auto_20240404_1227'),
        ('notices', '0006_transactionalconsideration_total_taxable'),
    ]

    operations = [
    ]
