# Generated by Django 3.2.23 on 2024-04-08 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0007_merge_20240405_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valuationconsideration',
            old_name='commitment',
            new_name='unfunded_commitment',
        ),
    ]
