# Generated by Django 3.2.25 on 2024-06-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0008_rename_commitment_valuationconsideration_unfunded_commitment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='valuationconsideration',
            name='unique_valuation_considerations',
        ),
        migrations.AddField(
            model_name='valuationconsideration',
            name='notice_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='valuationconsideration',
            constraint=models.UniqueConstraint(fields=('fund_id', 'firm_id', 'investor_id', 'notice_date'), name='unique_valuation_considerations'),
        ),
    ]
