# Generated by Django 3.2.18 on 2023-05-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0058_merge_20230512_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='wait_for_approval',
            field=models.BooleanField(default=True),
        ),
    ]
