# Generated by Django 3.2.18 on 2023-06-08 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0059_fund_wait_for_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundshareclass',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_share_classes', to='funds.fund'),
        ),
    ]
