# Generated by Django 3.2.18 on 2023-06-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0060_alter_fundshareclass_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='funddocumentresponse',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='funddocumentresponse',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='funddocumentresponse',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('fund', 'user'), name='unique_fund_user_validation'),
        ),
    ]
