# Generated by Django 3.2.18 on 2023-06-16 07:15

from django.db import migrations


def update_share_class_non_ascii_dash(apps, schema_editor):
    FundShareClass = apps.get_model('funds', 'FundShareClass')
    share_classes = FundShareClass.objects.all()
    for share_class in share_classes:
        if not share_class.display_name:
            continue

        if share_class.display_name.isascii():
            continue

        share_class.display_name = share_class.display_name.replace('\u2013', '-')
        if share_class.legal_name:
            share_class.legal_name = share_class.legal_name.replace('\u2013', '-')

        share_class.save()


class Migration(migrations.Migration):
    dependencies = [
        ('funds', '0061_auto_20230609_0819'),
    ]

    operations = [
        migrations.RunPython(update_share_class_non_ascii_dash, reverse_code=migrations.RunPython.noop)
    ]
