# Generated by Django 3.2.20 on 2023-07-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0062_auto_20230616_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundshareclass',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
