# Generated by Django 3.2.20 on 2023-08-28 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0059_auto_20230515_1004'),
        ('funds', '0062_auto_20230616_0715'),
    ]

    operations = [
    ]
