# Generated by Django 3.2.18 on 2023-08-30 12:57

import api.libs.utils.nanoid_generator
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geographics', '0009_address'),
        ('admin_users', '0006_auto_20230103_1142'),
        ('companies', '0042_auto_20230706_2028'),
        ('currencies', '0002_alter_currencyrate_rate_date'),
        ('funds', '0063_fundshareclass_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFund',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('modified_at', models.DateTimeField(blank=True, editable=False)),
                ('name', models.CharField(max_length=120)),
                ('partner_id', models.CharField(db_index=True, max_length=250)),
                ('investment_product_code', models.CharField(blank=True, max_length=250, null=True)),
                ('raw_investment_product_code', models.CharField(blank=True, max_length=250, null=True)),
                ('vehicle_code', models.CharField(blank=True, max_length=250, null=True)),
                ('external_id', models.CharField(db_index=True, default=api.libs.utils.nanoid_generator.generate_nanoid, max_length=14)),
                ('symbol', models.CharField(blank=True, max_length=120, null=True)),
                ('slug', models.CharField(db_index=True, max_length=120)),
                ('business_line', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Americas Private'), (2, 'Asia Pacific Private'), (3, 'Europe Private'), (4, 'Global Partner Solutions'), (5, 'Global Securities')], null=True)),
                ('demand', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=13, null=True)),
                ('unsold', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=13, null=True)),
                ('sold', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('existing_investors', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('county_code', models.CharField(blank=True, max_length=3, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('application_period_start_date', models.DateField(blank=True, null=True)),
                ('application_period_end_date', models.DateField(blank=True, null=True)),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('anticipated_first_call_date', models.DateField(blank=True, null=True)),
                ('interest_rate', models.FloatField(blank=True, null=True)),
                ('leverage_ratio', models.FloatField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_legacy', models.BooleanField(default=False)),
                ('target_fund_size', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('firm_co_investment_commitment', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('focus_region', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(blank=True, max_length=250, null=True)),
                ('risk_profile', models.CharField(blank=True, max_length=250, null=True)),
                ('investment_period', models.CharField(blank=True, max_length=250, null=True)),
                ('fund_page', models.URLField(blank=True, max_length=250, null=True)),
                ('minimum_investment', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=13, null=True)),
                ('fund_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Open End, Private Equity'), (2, 'Closed End, Private Equity')], null=True)),
                ('is_invite_only', models.BooleanField(blank=True, default=False, null=True)),
                ('is_finalized', models.BooleanField(blank=True, default=False, null=True)),
                ('offer_leverage', models.BooleanField(default=True)),
                ('publish_investment_details', models.BooleanField(default=False)),
                ('accept_applications', models.BooleanField(default=False)),
                ('close_applications', models.BooleanField(default=False)),
                ('open_for_indication_interest', models.BooleanField(default=False)),
                ('logo', models.TextField(blank=True, max_length=100, null=True)),
                ('investment_description', models.TextField(blank=True, null=True)),
                ('is_nav_disabled', models.BooleanField(blank=True, default=False, null=True)),
                ('target_irr', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('strategy', models.CharField(blank=True, max_length=250, null=True)),
                ('stats_json', models.JSONField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('banner_image', models.TextField(blank=True, max_length=100, null=True)),
                ('enable_internal_tax_flow', models.BooleanField(default=False)),
                ('skip_tax', models.BooleanField(default=False)),
                ('wait_for_approval', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='admin_users.adminuser')),
                ('domicile', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='geographics.country')),
                ('fund_currency', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='currencies.currency')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('managed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='companies.companyuser')),
            ],
            options={
                'verbose_name': 'historical fund',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
