# Generated by Django 3.2.18 on 2023-09-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0064_historicalfund'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalfund',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
