# Generated by Django 3.2.20 on 2023-10-17 10:14

import api.funds.models
from django.db import migrations, models
import django.db.models.deletion


def apply(apps, schema_editor):
    FundShareClass = apps.get_model('funds', 'FundShareClass')
    LeverageOption = apps.get_model('funds', 'LeverageOption')
    for share_class in FundShareClass.objects.all():
        print(f"sarasa {share_class}")
        leverage_option = LeverageOption.objects.filter(fund=share_class.fund, amount=int(share_class.leverage))
        if not leverage_option.exists():
            LeverageOption.objects.create(fund=share_class.fund, amount=int(share_class.leverage), description='')


def rollback(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0065_auto_20230918_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeverageOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField(help_text='Leverage amount')),
                ('description', models.CharField(default='', help_text='What characterizes this option if there are more with the same amount', max_length=255)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leverage_options', to='funds.fund')),
            ],
            options={
                'db_table': 'fund_leverage_options',
                'unique_together': {('fund', 'amount', 'description')},
            },
        ),
        migrations.RunPython(code=apply, reverse_code=rollback),
    ]
