# Generated by Django 3.2.20 on 2023-10-04 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0063_merge_0059_auto_20230515_1004_0062_auto_20230616_0715'),
        ('funds', '0065_auto_20230918_1118'),
    ]

    operations = [
    ]
