# Generated by Django 3.2.22 on 2023-10-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0065_auto_20230918_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='display_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='historicalfund',
            name='display_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
