# Generated by Django 3.2.20 on 2023-10-17 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0066_auto_20231016_1841'),
        ('funds', '0066_auto_20231017_1014'),
    ]

    operations = [
    ]
