# Generated by Django 3.2.20 on 2023-10-19 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0066_auto_20231016_1841'),
        ('funds', '0066_merge_20231004_1702'),
    ]

    operations = [
    ]
