# Generated by Django 3.2.22 on 2023-10-30 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0067_merge_0066_auto_20231016_1841_0066_auto_20231017_1014'),
        ('funds', '0067_merge_20231019_1808'),
    ]

    operations = [
    ]
