# Generated by Django 3.2.21 on 2023-11-03 06:41

import api.funds.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0068_merge_20231030_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='employee_co_invest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalfund',
            name='employee_co_invest',
            field=models.BooleanField(default=True),
        ),
    ]
