# Generated by Django 3.2.22 on 2023-11-07 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0068_auto_20231026_1524'),
        ('funds', '0069_auto_20231103_0641'),
    ]

    operations = [
    ]
