# Generated by Django 3.2.19 on 2024-01-29 10:41
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0071_auto_20240118_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='historicalfund',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
    ]
