# Generated by Django 3.2.23 on 2024-03-18 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0001_initial'),
        ('funds', '0072_auto_20240129_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firm_funds', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='historicalfund',
            name='firm',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='firms.firm'),
        ),
    ]
