# Generated by Django 3.2.23 on 2024-04-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0073_auto_20240318_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='created_via_partner_api',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalfund',
            name='created_via_partner_api',
            field=models.BooleanField(default=False),
        ),
    ]
