# Generated by Django 3.2.25 on 2024-04-24 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0074_auto_20240418_2037'),
        ('funds', '0074_auto_20240422_0948'),
    ]

    operations = [
    ]
