# Generated by Django 3.2.23 on 2024-05-07 11:02

import api.funds.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0075_merge_0074_auto_20240418_2037_0074_auto_20240422_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundshareclass',
            name='internal_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
