# Generated by Django 3.2.19 on 2024-06-10 10:28

import api.funds.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0076_auto_20240507_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='max_levered_commitment_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='historicalfund',
            name='max_levered_commitment_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
    ]
