# Generated by Django 3.2.25 on 2024-08-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0077_auto_20240610_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='fair_market_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='historicalfund',
            name='fair_market_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
    ]
