# Generated by Django 3.2.25 on 2024-11-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0078_auto_20240822_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='estimated_value_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='fair_market_value_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfund',
            name='estimated_value_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfund',
            name='fair_market_value_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
