# Generated by Django 3.2.25 on 2024-12-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0079_auto_20241125_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='cashless_commitment_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalfund',
            name='cashless_commitment_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
