# Generated by Django 3.2.25 on 2025-02-10 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0047_alter_company_logo'),
        ('funds', '0080_auto_20241218_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyImporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('importer_name', models.CharField(max_length=255)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='importer', to='companies.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
