# Generated by Django 3.2.25 on 2025-03-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0081_companyimporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='min_leverage_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='historicalfund',
            name='min_leverage_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
    ]
