# Generated by Django 3.2.25 on 2025-05-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0082_auto_20250326_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='county_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfund',
            name='county_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
