# Generated by Django 3.2.25 on 2025-05-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0083_auto_20250509_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='skip_net_worth_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalfund',
            name='skip_net_worth_question',
            field=models.BooleanField(default=False),
        ),
    ]
