# Generated by Django 3.2.23 on 2024-04-16 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0002_alter_currencyrate_rate_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0046_alter_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('salary', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('bonus', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('health_and_wellness', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('match_401k', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_compensation_records', to='companies.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='currencies.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='compensationrecord',
            constraint=models.UniqueConstraint(fields=('user_id', 'company_id', 'year'), name='unique_compensation_records'),
        ),
    ]
