# Generated by Django 3.2.23 on 2024-06-03 08:59

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compensation_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('salary', api.models.EncryptedDecimalField(decimal_places=8, default=0, max_digits=18)),
                ('bonus', api.models.EncryptedDecimalField(decimal_places=8, default=0, max_digits=18)),
                ('extra_bonus', api.models.EncryptedDecimalField(decimal_places=8, default=0, max_digits=18)),
                ('match_401k', api.models.EncryptedDecimalField(decimal_places=8, default=0, max_digits=18)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompensationTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('fica', api.models.EncryptedDecimalField(decimal_places=8, default=0, max_digits=18)),
                ('medicare', api.models.EncryptedDecimalField(decimal_places=8, default=0, max_digits=18)),
                ('futa', api.models.EncryptedDecimalField(decimal_places=8, default=0, max_digits=18)),
                ('sui', api.models.EncryptedDecimalField(decimal_places=8, default=0, max_digits=18)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsuranceBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('medical', api.models.EncryptedDecimalField(decimal_places=8, default=0, max_digits=18)),
                ('dental', api.models.EncryptedDecimalField(decimal_places=8, default=0, max_digits=18)),
                ('vision', api.models.EncryptedDecimalField(decimal_places=8, default=0, max_digits=18)),
                ('life', api.models.EncryptedDecimalField(decimal_places=8, default=0, max_digits=18)),
                ('ad_and_d', api.models.EncryptedDecimalField(decimal_places=8, default=0, max_digits=18)),
                ('std', api.models.EncryptedDecimalField(decimal_places=8, default=0, max_digits=18)),
                ('ltd', api.models.EncryptedDecimalField(decimal_places=8, default=0, max_digits=18)),
                ('supplemental_ltd', api.models.EncryptedDecimalField(decimal_places=8, default=0, max_digits=18)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MiscellaneousBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('phone', api.models.EncryptedDecimalField(decimal_places=8, default=0, max_digits=18)),
                ('meals', api.models.EncryptedDecimalField(decimal_places=8, default=0, max_digits=18)),
                ('parking', api.models.EncryptedDecimalField(decimal_places=8, default=0, max_digits=18)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='compensationrecord',
            name='unique_compensation_records',
        ),
        migrations.RemoveField(
            model_name='compensationrecord',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='compensationrecord',
            name='health_and_wellness',
        ),
        migrations.RemoveField(
            model_name='compensationrecord',
            name='match_401k',
        ),
        migrations.RemoveField(
            model_name='compensationrecord',
            name='salary',
        ),
        migrations.AddField(
            model_name='compensationrecord',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='compensationrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('user_id', 'company_id', 'year'), name='unique_compensation_records'),
        ),
        migrations.AddField(
            model_name='miscellaneousbenefit',
            name='compensation_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='misc_benefits', to='compensation_records.compensationrecord'),
        ),
        migrations.AddField(
            model_name='insurancebenefit',
            name='compensation_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_benefits', to='compensation_records.compensationrecord'),
        ),
        migrations.AddField(
            model_name='compensationtax',
            name='compensation_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='compensation_records.compensationrecord'),
        ),
        migrations.AddField(
            model_name='cash',
            name='compensation_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash', to='compensation_records.compensationrecord'),
        ),
    ]
