export const ADMIN_PATH = '/admin/dashboard'
export const FUNDS_PATH = '/admin/funds'
export const COMPANY_PATH = '/admin/company'
export const USERS_PATH = '/admin/users'
export const PARTICIPANTS_PATH = '/admin/participants'
export const CARRY_MANAGEMENT_PATH = '/admin/carryManagement'
