# Generated by Django 3.2.23 on 2024-05-02 11:40

from django.db import migrations

from api.users.constants import COMPENSATION_ADMIN


def create_compensation_admin_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name=COMPENSATION_ADMIN)

class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0006_auto_20230103_1142'),
    ]

    operations = [
        migrations.RunPython(create_compensation_admin_group, reverse_code=migrations.RunPython.noop)
    ]
