# Generated by Django 3.2.25 on 2025-02-25 11:33

from django.db import migrations
from api.users.constants import CARRY_MANAGER


def create_carry_manager_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name=CARRY_MANAGER)


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0007_auto_20240502_1140'),
    ]

    operations = [
        migrations.RunPython(create_carry_manager_group, reverse_code=migrations.RunPython.noop)
    ]
