# Generated by Django 3.2.25 on 2024-07-04 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0077_auto_20240610_1028'),
        ('backup', '0002_fundbackup_funddocumentsbackup'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamoFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('dynamo_id', models.CharField(db_index=True, max_length=250, null=True)),
                ('fund', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dynamo_fund', to='funds.fund')),
            ],
            options={
                'db_table': 'dynamo_funds',
            },
        ),
    ]
