# Generated by Django 3.2.25 on 2024-10-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital_calls', '0007_auto_20230313_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalcall',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
