# Generated by Django 3.2.25 on 2025-02-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital_calls', '0008_capitalcall_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalcall',
            name='commitment_type',
            field=models.CharField(blank=True, choices=[('cash', 'Other'), ('offset', 'Offset')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalcall',
            name='deal_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalcall',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
