# Generated by Django 3.2.25 on 2025-02-18 07:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0048_company_show_new_commitment_flow'),
        ('funds', '0081_companyimporter'),
        ('investors', '0036_auto_20250217_1058'),
        ('capital_calls', '0009_auto_20250217_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField()),
                ('call_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('deal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('is_recallable', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_distributions', to='companies.company')),
                ('company_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_distributions', to='companies.companyuser')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_distributions', to='funds.fund')),
                ('fund_investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_distributions', to='investors.fundinvestor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
