# Generated by Django 3.2.25 on 2025-02-19 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capital_calls', '0010_distribution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capitalcall',
            options={'ordering': ('-number', '-id')},
        ),
        migrations.AlterModelOptions(
            name='distribution',
            options={'ordering': ('-number', '-id')},
        ),
    ]
