# Generated by Django 3.2.25 on 2025-05-15 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0037_auto_20250515_0950'),
        ('companies', '0048_company_show_new_commitment_flow'),
        ('capital_calls', '0011_auto_20250219_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalcall',
            name='capital_call_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalcall',
            name='cash_called',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='capitalcall',
            name='loan_called',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='capitalcall',
            name='management_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='capitalcall',
            name='offset_called',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='capitalcall',
            name='total_called',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='distribution',
            name='cash_loan_offset_gain',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='distribution',
            name='cash_returned',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='distribution',
            name='due_for_gp_loan',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='distribution',
            name='loan_returned',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='distribution',
            name='offset_returned',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='distribution',
            name='recallable',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distribution',
            name='total_proceeds',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('total_commitment', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('cash_commitment', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('offset_commitment', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('loan_commitment', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_commitments', to='companies.company')),
                ('company_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_commitments', to='companies.companyuser')),
                ('fund_investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_commitments', to='investors.fundinvestor')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
