# Generated by Django 3.2.25 on 2025-05-27 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capital_calls', '0013_auto_20250527_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commitment',
            old_name='conversion_date',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='historicalcommitment',
            old_name='conversion_date',
            new_name='due_date',
        ),
        migrations.RemoveField(
            model_name='capitalcall',
            name='conversion_date',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='conversion_date',
        ),
        migrations.RemoveField(
            model_name='historicalcapitalcall',
            name='conversion_date',
        ),
        migrations.RemoveField(
            model_name='historicaldistribution',
            name='conversion_date',
        ),
    ]
