# Generated by Django 3.2.25 on 2025-06-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital_calls', '0014_auto_20250527_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalcall',
            name='production_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='capitalcall',
            name='staging_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='capitalcalldetail',
            name='production_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='capitalcalldetail',
            name='staging_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='commitment',
            name='production_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='commitment',
            name='staging_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='distribution',
            name='production_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='distribution',
            name='staging_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fundcapitalcall',
            name='production_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fundcapitalcall',
            name='staging_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='historicalcapitalcall',
            name='production_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcapitalcall',
            name='staging_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcommitment',
            name='production_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcommitment',
            name='staging_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldistribution',
            name='production_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldistribution',
            name='staging_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
