# Generated by Django 3.2.18 on 2024-03-26 10:52

from django.db import migrations


def rename_W9(apps, schema_editor):
    TaxForm = apps.get_model('tax_records', 'TaxForm')
    TaxForm.objects.filter(form_id='W-9').update(
        file_name='W-9-03.2024.pdf',
        version='03.2024'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tax_records', '0015_taxform_help_link'),
    ]

    operations = [
        migrations.RunPython(rename_W9),
    ]
